'use client';
import { useActionState } from 'react';
import { AddDrawer } from '@/components/Drawer';
import { FormMessage } from '@/components/FormMessage';
import { INITIAL_ACTION_STATE } from '@/lib/action-result';
import { createLoanPaymentAction } from '@/actions/loan-payment-actions';
import type { Loan } from '@/lib/loans';
import type { LoanPayment } from '@/lib/loan-payments';
const won = new Intl.NumberFormat('ko-KR');
export function LoanPaymentManager({ loans, payments, today }: { loans: Loan[]; payments: LoanPayment[]; today: string }) { return <section className="tds-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-bold">실제 상환내역</h2><p className="mt-1 text-sm text-[var(--tds-grey-700)]">예정 상환표와 실제 조기상환·대환·완납 기록을 분리해 관리합니다.</p></div><AddDrawer title="상환내역 추가" description="실제 상환한 원금과 이자를 기록합니다." triggerLabel="상환내역 추가"><PaymentForm loans={loans} today={today} /></AddDrawer></div>{payments.length === 0 ? <p className="mt-5 text-sm text-[var(--tds-grey-500)]">기록된 실제 상환내역이 없습니다.</p> : <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b text-left text-xs text-[var(--tds-grey-500)]"><th className="py-3">상환일</th><th>대출</th><th>구분</th><th className="text-right">원금</th><th className="text-right">이자</th><th className="text-right">잔액</th></tr></thead><tbody>{payments.map((payment) => <tr key={payment.id} className="border-b border-[var(--tds-grey-100)]"><td className="py-3">{payment.paymentDate}</td><td>{loans.find((loan) => loan.id === payment.loanId)?.loanName ?? '알 수 없는 대출'}</td><td>{payment.paymentType === 'early' ? '조기상환' : payment.paymentType === 'refinance' ? '대환' : payment.paymentType === 'payoff' ? '완납' : '정기상환'}</td><td className="text-right tabular-nums">{won.format(payment.principalPayment)}원</td><td className="text-right tabular-nums">{won.format(payment.interestPayment)}원</td><td className="text-right tabular-nums">{won.format(payment.remainingBalance)}원</td></tr>)}</tbody></table></div>}</section>; }
function PaymentForm({ loans, today }: { loans: Loan[]; today: string }) { const [state, action, pending] = useActionState(createLoanPaymentAction, INITIAL_ACTION_STATE); return <form action={action} className="grid gap-4"><FormMessage result={state} /><label className="flex flex-col gap-1 text-sm font-medium">대출<select name="loanId" required className="px-3">{loans.map((loan) => <option key={loan.id} value={loan.id}>{loan.loanName}</option>)}</select></label><label className="flex flex-col gap-1 text-sm font-medium">상환일<input name="paymentDate" type="date" defaultValue={today} required /></label><label className="flex flex-col gap-1 text-sm font-medium">회차<input name="installment" type="number" min="1" step="1" defaultValue="1" required placeholder="1" /></label><label className="flex flex-col gap-1 text-sm font-medium">상환구분<select name="paymentType" className="px-3"><option value="scheduled">정기상환</option><option value="early">조기상환</option><option value="refinance">대환</option><option value="payoff">완납</option></select></label><label className="flex flex-col gap-1 text-sm font-medium">상환원금<input name="principalPayment" type="number" min="0" step="1" required placeholder="0" /></label><label className="flex flex-col gap-1 text-sm font-medium">이자<input name="interestPayment" type="number" min="0" step="1" required placeholder="0" /></label><label className="flex flex-col gap-1 text-sm font-medium">누적상환액<input name="cumulativePayment" type="number" min="0" step="1" required placeholder="0" /></label><label className="flex flex-col gap-1 text-sm font-medium">상환 후 잔액<input name="remainingBalance" type="number" min="0" step="1" required placeholder="0" /></label><label className="flex flex-col gap-1 text-sm font-medium">메모<input name="memo" placeholder="메모 (선택)" /></label><button disabled={pending} className="tds-primary-button">{pending ? '저장 중...' : '상환내역 저장'}</button></form>; }
