import { normalizeImportAmount, normalizeImportDate } from '@/lib/transaction-import';

export type ParsedLoan = { rowNumber: number; institutionName: string; loanName: string; originalAmount: number | null; annualRate: number | null; repaymentMethod: 'equal_payment' | 'equal_principal' | 'bullet'; loanDate: string | null; firstPaymentDate: string | null; maturityDate: string | null; errors: string[] };
export type ParsedInsurance = { rowNumber: number; insuredMember: string; insurerName: string; insuranceType: string; productName: string; coverageSummary: string | null; paymentMethodNote: string | null; joinedAt: string | null; paymentMaturityDate: string | null; coverageMaturityDate: string | null; monthlyPremium: number | null; errors: string[] };
const norm = (value: unknown) => String(value ?? '').normalize('NFKC').toLowerCase().replace(/[\s_\-()[\]{}:/\\.]/g, '');
const col = (headers: unknown[], names: string[]) => headers.findIndex((value) => names.some((name) => norm(value) === norm(name) || norm(value).includes(norm(name))));
function locate(rows: unknown[][], names: Record<string, string[]>) { for (let index = 0; index < Math.min(rows.length, 50); index += 1) { const result = Object.fromEntries(Object.entries(names).map(([key, values]) => [key, col(rows[index] ?? [], values)])); if (Object.values(result).every((value) => value >= 0)) return { index, result: result as Record<keyof typeof names, number> }; } return null; }
const money = (value: unknown) => { const parsed = normalizeImportAmount(value); return parsed.amount === null ? null : parsed.negative ? -parsed.amount : parsed.amount; };
const percent = (value: unknown) => { const parsed = Number(String(value ?? '').replace('%', '')); return Number.isFinite(parsed) ? parsed / (parsed > 1 ? 100 : 1) : null; };
export function parseLoanRows(rows: unknown[][]): ParsedLoan[] { const found = locate(rows, { institution: ['기관명', '금융기관'], name: ['대출명'], amount: ['대출금액'], rate: ['연이자율', '금리'], loanDate: ['대출일'], maturity: ['상환만기일', '만기일'] }); if (!found) return []; const schedule = locate(rows, { installment: ['회차'], paymentDate: ['상환일'], principal: ['납입원금'], interest: ['대출이자'] }); const firstPaymentDate = schedule ? normalizeImportDate(rows[schedule.index + 1]?.[schedule.result.paymentDate]) : null; return rows.slice(found.index + 1, schedule?.index ?? rows.length).flatMap((row, offset) => { if (!row.some((value) => String(value ?? '').trim()) || !String(row[found.result.institution] ?? '').trim()) return []; const institutionName = String(row[found.result.institution] ?? '').trim(); const loanName = String(row[found.result.name] ?? '').trim(); const originalAmount = money(row[found.result.amount]); const annualRate = percent(row[found.result.rate]); const loanDate = normalizeImportDate(row[found.result.loanDate]); const maturityDate = normalizeImportDate(row[found.result.maturity]); const methodText = norm(row[found.result.name]) + norm(row[found.result.institution]); const repaymentMethod = methodText.includes('만기') ? 'bullet' : 'equal_payment'; const errors = [!loanName && '대출명을 확인해 주세요.', originalAmount === null && '대출금액을 확인해 주세요.', annualRate === null && '연이자율을 확인해 주세요.', !loanDate && '대출일을 확인해 주세요.', !firstPaymentDate && '첫 상환일을 확인해 주세요.', !maturityDate && '만기일을 확인해 주세요.'].filter(Boolean) as string[]; return [{ rowNumber: found.index + offset + 2, institutionName, loanName, originalAmount, annualRate, repaymentMethod, loanDate, firstPaymentDate, maturityDate, errors }]; }); }
export function parseInsuranceRows(rows: unknown[][]): ParsedInsurance[] { const found = locate(rows, { member: ['피보험자'], insurer: ['보험사'], type: ['종류'], product: ['보험명'], coverage: ['보장내역'], payment: ['납부방법'], joined: ['가입일'], paymentMaturity: ['납입만기'], coverageMaturity: ['보험만기'], premium: ['월보험료'] }); if (!found) return []; return rows.slice(found.index + 1).flatMap((row, offset) => { if (!row.some((value) => String(value ?? '').trim()) || !String(row[found.result.insurer] ?? '').trim()) return []; const get = (key: keyof typeof found.result) => String(row[found.result[key]] ?? '').trim(); const monthlyPremium = money(row[found.result.premium]); const joinedAt = normalizeImportDate(row[found.result.joined]); const errors = [!get('product') && '보험명을 확인해 주세요.', !get('type') && '보험종류를 확인해 주세요.', !joinedAt && '가입일을 확인해 주세요.', monthlyPremium === null && '월보험료를 확인해 주세요.'].filter(Boolean) as string[]; return [{ rowNumber: found.index + offset + 2, insuredMember: get('member'), insurerName: get('insurer'), insuranceType: get('type'), productName: get('product'), coverageSummary: get('coverage') || null, paymentMethodNote: get('payment') || null, joinedAt, paymentMaturityDate: normalizeImportDate(row[found.result.paymentMaturity]), coverageMaturityDate: normalizeImportDate(row[found.result.coverageMaturity]), monthlyPremium, errors }]; }); }
