import { normalizeImportAmount, normalizeImportDate } from '@/lib/transaction-import';

export type ParsedSupport = { rowNumber: number; supportKind: string; eligibility: string | null; applicationPeriod: string | null; receivingPeriod: string | null; amountPerOccurrence: number | null; totalExpectedAmount: number | null; status: string; issuer: string | null; memo: string | null; errors: string[] };
export type ParsedEvent = { rowNumber: number; eventType: 'wedding' | 'condolence' | 'gift' | 'other'; eventDate: string | null; description: string; amount: number | null; errors: string[] };
const text = (value: unknown) => String(value ?? '').trim();
const money = (value: unknown) => { const result = normalizeImportAmount(value); return result.amount === null ? null : result.negative ? -result.amount : result.amount; };
export function parseSupportRows(rows: unknown[][]): ParsedSupport[] { const headerIndex = rows.findIndex((row) => row.some((value) => text(value) === '지원금종류')); if (headerIndex < 0) return []; const header = rows[headerIndex] ?? []; const find = (label: string) => header.findIndex((value) => text(value).includes(label)); const c = { kind: find('지원금종류'), eligibility: find('자격'), application: find('신청기간'), receiving: find('사용기간'), amount: find('금액'), total: find('총 지원금'), status: find('지급여부'), issuer: find('접수처') }; return rows.slice(headerIndex + 1).flatMap((row, offset) => { const supportKind = text(row[c.kind]); if (!supportKind) return []; const amountPerOccurrence = c.amount >= 0 ? money(row[c.amount]) : null; const totalExpectedAmount = c.total >= 0 ? money(row[c.total]) : null; const errors = [amountPerOccurrence === null && totalExpectedAmount === null && '금액 정보를 확인해 주세요.'].filter(Boolean) as string[]; return [{ rowNumber: headerIndex + offset + 2, supportKind, eligibility: c.eligibility >= 0 ? text(row[c.eligibility]) || null : null, applicationPeriod: c.application >= 0 ? text(row[c.application]) || null : null, receivingPeriod: c.receiving >= 0 ? text(row[c.receiving]) || null : null, amountPerOccurrence, totalExpectedAmount, status: c.status >= 0 ? text(row[c.status]) : '', issuer: c.issuer >= 0 ? text(row[c.issuer]) || null : null, memo: null, errors }]; }); }
function eventType(value: string): ParsedEvent['eventType'] { return value.includes('결혼') || value.includes('축의') ? 'wedding' : value.includes('상') || value.includes('부조') || value.includes('부의') ? 'condolence' : value.includes('선물') ? 'gift' : 'other'; }
export function parseEventRows(rows: unknown[][]): ParsedEvent[] { const headerIndex = rows.findIndex((row) => row.filter((value) => text(value)).some((value) => text(value) === '날짜') && row.filter((value) => text(value)).some((value) => text(value) === '내용')); if (headerIndex < 0) return []; const header = rows[headerIndex] ?? []; const blocks: Array<{ date: number; description: number; amount: number }> = []; for (let start = 0; start < header.length; start += 1) { if (text(header[start]) === '날짜' && text(header[start + 1]) === '내용' && text(header[start + 2]) === '금액') blocks.push({ date: start, description: start + 1, amount: start + 2 }); } return rows.slice(headerIndex + 1).flatMap((row, offset) => blocks.flatMap((block) => { const description = text(row[block.description]); if (!description) return []; const amount = money(row[block.amount]); return [{ rowNumber: headerIndex + offset + 2, eventType: eventType(description), eventDate: normalizeImportDate(row[block.date]), description, amount, errors: [!normalizeImportDate(row[block.date]) && '날짜를 확인해 주세요.', amount === null && '금액을 확인해 주세요.'].filter(Boolean) as string[] }]; })); }
