import { normalizeImportAmount, normalizeImportDate } from '@/lib/transaction-import';

export type ParsedDeposit = { rowNumber: number; bankName: string; productName: string; joinedAt: string | null; maturityDate: string | null; principal: number | null; annualRate: number | null; taxRate: number | null; memo: string | null; errors: string[] };
export type ParsedSavings = { rowNumber: number; bankName: string; productName: string; joinedAt: string | null; maturityDate: string | null; monthlyAmount: number | null; annualRate: number | null; taxRate: number | null; currentSavings: number | null; memo: string | null; errors: string[] };
const normalize = (value: unknown) => String(value ?? '').normalize('NFKC').toLowerCase().replace(/[\s_\-()[\]{}:/\\.]/g, '');
const column = (headers: unknown[], options: string[]) => headers.findIndex((header) => options.some((option) => { const current = normalize(header); const target = normalize(option); return current === target || current.includes(target); }));
function locate(rows: unknown[][], required: Record<string, string[]>, maxRows: number) { for (let index = 0; index < Math.min(maxRows, rows.length); index += 1) { const headers = rows[index] ?? []; const columns = Object.fromEntries(Object.entries(required).map(([key, options]) => [key, column(headers, options)])); if (Object.entries(columns).filter(([key]) => key !== 'memo').every(([, value]) => Number(value) >= 0)) return { index, columns: columns as Record<keyof typeof required, number> }; } return null; }
const amount = (value: unknown) => { const parsed = normalizeImportAmount(value); return parsed.amount === null ? null : parsed.negative ? -parsed.amount : parsed.amount; };
const rate = (value: unknown) => { const parsed = Number(String(value ?? '').replace('%', '').trim()); if (!Number.isFinite(parsed)) return null; return parsed > 1 ? parsed / 100 : parsed; };
export function parseDepositRows(rows: unknown[][]): ParsedDeposit[] { const found = locate(rows, { bank: ['은행', 'bank'], product: ['예금명', '상품명', 'product'], joined: ['가입일', '가입일자'], maturity: ['만기일', '만기'], principal: ['원금', '예치금액'], rate: ['이율', '금리'], tax: ['과세', '세율'], memo: ['비고', '메모'] }, 40); if (!found) return []; return rows.slice(found.index + 1).flatMap((row, offset) => { if (!row.some((value) => String(value ?? '').trim()) || !String(row[found.columns.bank] ?? '').trim()) return []; const bankName = String(row[found.columns.bank] ?? '').trim(); const productName = String(row[found.columns.product] ?? '').trim(); const joinedAt = normalizeImportDate(row[found.columns.joined]); const maturityDate = normalizeImportDate(row[found.columns.maturity]); const principal = amount(row[found.columns.principal]); const annualRate = rate(row[found.columns.rate]); const taxRate = rate(row[found.columns.tax]); const errors = [!productName && '상품명을 확인해 주세요.', !joinedAt && '가입일을 확인해 주세요.', !maturityDate && '만기일을 확인해 주세요.', principal === null && '원금을 확인해 주세요.', annualRate === null && '이율을 확인해 주세요.'].filter(Boolean) as string[]; return [{ rowNumber: found.index + offset + 2, bankName, productName, joinedAt, maturityDate, principal, annualRate, taxRate: taxRate ?? 0, memo: found.columns.memo >= 0 ? String(row[found.columns.memo] ?? '').trim() || null : null, errors }]; }); }
export function parseSavingsRows(rows: unknown[][]): ParsedSavings[] { const found = locate(rows, { bank: ['은행', 'bank'], product: ['적금명', '상품명', 'product'], joined: ['가입일', '가입일자'], maturity: ['만기일', '만기'], monthly: ['월 적립액', '월적립액', '월납입액'], rate: ['이율', '금리'], tax: ['과세', '세율'], current: ['현재저축액', '현재 저축액', '현재금액'], memo: ['비고', '메모'] }, 40); if (!found) return []; return rows.slice(found.index + 1).flatMap((row, offset) => { if (!row.some((value) => String(value ?? '').trim()) || !String(row[found.columns.bank] ?? '').trim()) return []; const bankName = String(row[found.columns.bank] ?? '').trim(); const productName = String(row[found.columns.product] ?? '').trim(); const joinedAt = normalizeImportDate(row[found.columns.joined]); const maturityDate = normalizeImportDate(row[found.columns.maturity]); const monthlyAmount = amount(row[found.columns.monthly]); const annualRate = rate(row[found.columns.rate]); const taxRate = rate(row[found.columns.tax]); const currentSavings = amount(row[found.columns.current]); const errors = [!productName && '상품명을 확인해 주세요.', !joinedAt && '가입일을 확인해 주세요.', !maturityDate && '만기일을 확인해 주세요.', monthlyAmount === null && '월 적립액을 확인해 주세요.', currentSavings === null && '현재저축액을 확인해 주세요.'].filter(Boolean) as string[]; return [{ rowNumber: found.index + offset + 2, bankName, productName, joinedAt, maturityDate, monthlyAmount, annualRate, taxRate: taxRate ?? 0, currentSavings, memo: found.columns.memo >= 0 ? String(row[found.columns.memo] ?? '').trim() || null : null, errors }]; }); }
