import 'server-only';
import { createClient } from '@/lib/supabase/server';

export type InvestmentTrade = { id: string; tradeDate: string; assetName: string; tradeType: 'buy' | 'sell'; unitPrice: number; tradeAmount: number; fee: number; settledAmount: number; memo: string | null; source: string | null };
export type FinancialGoal = { id: string; goalYear: number; name: string; targetAmount: number | null; targetRatio: number | null; currentValue: number | null; targetDate: string | null; memo: string | null };
export type FinancialTask = { id: string; taskDate: string; title: string; description: string | null; completed: boolean; relatedType: string | null };

export async function listInvestmentTrades(householdId: string): Promise<InvestmentTrade[]> {
  const supabase = await createClient(); const { data, error } = await supabase.from('investment_transactions').select('id,trade_date,asset_name,trade_type,unit_price,trade_amount,fee,settled_amount,memo,source').eq('household_id', householdId).order('trade_date', { ascending: false });
  if (error) throw new Error(`투자 거래 조회 실패: ${error.message}`);
  return (data ?? []).map((r) => ({ id: r.id, tradeDate: r.trade_date, assetName: r.asset_name, tradeType: r.trade_type, unitPrice: Number(r.unit_price), tradeAmount: Number(r.trade_amount), fee: Number(r.fee), settledAmount: Number(r.settled_amount), memo: r.memo, source: r.source }));
}
export async function listFinancialGoals(householdId: string): Promise<FinancialGoal[]> { const supabase = await createClient(); const { data, error } = await supabase.from('financial_goals').select('id,goal_year,name,target_amount,target_ratio,current_value,target_date,memo').eq('household_id', householdId).order('target_date', { ascending: true, nullsFirst: false }); if (error) throw new Error(`재무 목표 조회 실패: ${error.message}`); return (data ?? []).map((r) => ({ id: r.id, goalYear: r.goal_year, name: r.name, targetAmount: r.target_amount, targetRatio: r.target_ratio, currentValue: r.current_value, targetDate: r.target_date, memo: r.memo })); }
export async function listFinancialTasks(householdId: string, from?: string, to?: string): Promise<FinancialTask[]> { const supabase = await createClient(); let q = supabase.from('financial_tasks').select('id,task_date,title,description,completed,related_type').eq('household_id', householdId).order('task_date', { ascending: true }); if (from) q = q.gte('task_date', from); if (to) q = q.lte('task_date', to); const { data, error } = await q; if (error) throw new Error(`재무 할 일 조회 실패: ${error.message}`); return (data ?? []).map((r) => ({ id: r.id, taskDate: r.task_date, title: r.title, description: r.description, completed: r.completed, relatedType: r.related_type })); }
export async function createFinancialGoal(input: { householdId: string; goalYear: number; name: string; targetAmount: number | null; targetRatio: number | null; targetDate: string | null; currentValue: number | null; memo: string | null }): Promise<void> { const supabase = await createClient(); const { error } = await supabase.from('financial_goals').insert({ household_id: input.householdId, goal_year: input.goalYear, name: input.name, target_amount: input.targetAmount, target_ratio: input.targetRatio, target_date: input.targetDate, current_value: input.currentValue, memo: input.memo }); if (error) throw new Error(`재무 목표 추가 실패: ${error.message}`); }
export async function createFinancialTask(input: { householdId: string; taskDate: string; title: string; description: string | null; relatedType: string | null }): Promise<void> { const supabase = await createClient(); const { error } = await supabase.from('financial_tasks').insert({ household_id: input.householdId, task_date: input.taskDate, title: input.title, description: input.description, related_type: input.relatedType }); if (error) throw new Error(`재무 일정 추가 실패: ${error.message}`); }
export async function updateFinancialTask(id: string, completed: boolean): Promise<void> { const supabase = await createClient(); const { error } = await supabase.from('financial_tasks').update({ completed }).eq('id', id).select('id').single(); if (error) throw new Error(`재무 일정 변경 실패: ${error.message}`); }
