import 'server-only';
import { listAccounts } from '@/lib/accounts'; import { listAssets } from '@/lib/assets'; import { listDeposits } from '@/lib/deposits'; import { listLoans } from '@/lib/loans'; import { listSavingsAccounts } from '@/lib/savings'; import { buildAmortizationSchedule, findCurrentSnapshot, paymentMonthsInclusive } from '@/lib/loan-calculations'; import { calculateNetWorth, type NetWorthSummary } from '@/lib/net-worth'; import { createClient } from '@/lib/supabase/server';
export type AssetSnapshot = NetWorthSummary & { id: string; snapshotMonth: string };
export type AssetValueHistory = { id: string; snapshotMonth: string; totalAssets: number; source: string };
export async function computeCurrentNetWorth(householdId: string, today: string, memberId?: string): Promise<NetWorthSummary> {
  const [accounts, deposits, savings, assets, loans] = await Promise.all([listAccounts(householdId), listDeposits(householdId), listSavingsAccounts(householdId), listAssets(householdId), listLoans(householdId)]);
  const selectedOwner = memberId === 'unassigned' ? null : memberId;
  const belongsToSelectedMember = (ownerMemberId: string | null) => memberId === undefined || ownerMemberId === selectedOwner;
  const totalDebt = loans.filter((l) => l.status === 'active' && belongsToSelectedMember(l.ownerMemberId)).reduce((sum, loan) => { const schedule = buildAmortizationSchedule({ principal: loan.originalAmount, annualRate: loan.annualRate, termMonths: paymentMonthsInclusive(loan.firstPaymentDate, loan.maturityDate), graceMonths: loan.graceMonths, method: loan.repaymentMethod, firstPaymentDate: loan.firstPaymentDate }); return sum + (findCurrentSnapshot(schedule, today)?.remainingBalance ?? loan.originalAmount); }, 0);
  const activeAccounts = accounts.filter((account) => account.status === 'active' && belongsToSelectedMember(account.ownerMemberId));
  return calculateNetWorth({
    cashAssets: activeAccounts.filter((account) => ['checking', 'savings', 'cma'].includes(account.accountType)).reduce((sum, account) => sum + account.currentBalance, 0),
    depositAssets: deposits.filter((deposit) => deposit.status === 'active' && belongsToSelectedMember(deposit.ownerMemberId)).reduce((sum, deposit) => sum + deposit.principal, 0),
    savingsAssets: savings.filter((saving) => saving.status === 'active' && belongsToSelectedMember(saving.ownerMemberId)).reduce((sum, saving) => sum + saving.currentSavings, 0),
    investmentAssets: activeAccounts.filter((account) => !['checking', 'savings', 'cma'].includes(account.accountType)).reduce((sum, account) => sum + account.currentBalance, 0),
    nonFinancialAssets: assets.filter((asset) => asset.status === 'active' && belongsToSelectedMember(asset.ownerMemberId)).reduce((sum, asset) => sum + asset.currentValue, 0),
    totalDebt,
  });
}
export async function saveMonthlySnapshot(householdId: string, today: string): Promise<void> { const summary = await computeCurrentNetWorth(householdId, today); const supabase = await createClient(); const { error } = await supabase.from('monthly_asset_snapshots').upsert({ household_id: householdId, snapshot_month: `${today.slice(0, 7)}-01`, cash_assets: summary.cashAssets, deposit_assets: summary.depositAssets, savings_assets: summary.savingsAssets, investment_assets: summary.investmentAssets, non_financial_assets: summary.nonFinancialAssets, total_assets: summary.totalAssets, total_debt: summary.totalDebt, net_worth: summary.netWorth }, { onConflict: 'household_id,snapshot_month' }); if (error) throw new Error(`자산 스냅샷 저장 실패: ${error.message}`); }
export async function listRecentSnapshots(householdId: string, limit = 13): Promise<AssetSnapshot[]> { const supabase = await createClient(); const { data, error } = await supabase.from('monthly_asset_snapshots').select('id, snapshot_month, cash_assets, deposit_assets, savings_assets, investment_assets, non_financial_assets, total_assets, total_debt, net_worth').eq('household_id', householdId).order('snapshot_month', { ascending: false }).limit(limit); if (error) throw new Error(`자산 스냅샷 조회 실패: ${error.message}`); return (data ?? []).map((r) => { const summary = calculateNetWorth({ cashAssets: r.cash_assets, depositAssets: r.deposit_assets, savingsAssets: r.savings_assets, investmentAssets: r.investment_assets, nonFinancialAssets: r.non_financial_assets, totalDebt: r.total_debt }); return { ...summary, id: r.id, snapshotMonth: r.snapshot_month }; }); }
export async function listAssetValueHistory(householdId: string, limit = 36): Promise<AssetValueHistory[]> { const supabase = await createClient(); const { data, error } = await supabase.from('asset_value_history').select('id, snapshot_month, total_assets, source').eq('household_id', householdId).order('snapshot_month', { ascending: false }).limit(limit); if (error) throw new Error(`자산 추이 조회 실패: ${error.message}`); return (data ?? []).map((r) => ({ id: r.id, snapshotMonth: r.snapshot_month, totalAssets: r.total_assets, source: r.source })); }
