import 'server-only';
import { createClient } from '@/lib/supabase/server';

export type SupportDetail = { transactionId: string; supportKind: string; eligibility: string | null; applicationPeriod: string | null; receivingPeriod: string | null; payoutCycle: string | null; expectedDate: string | null; amountPerOccurrence: number | null; totalExpectedAmount: number | null; status: string; issuer: string | null; contact: string | null; sourceUrl: string | null; memo: string | null };
export type EventDetail = { transactionId: string; eventType: 'wedding' | 'condolence' | 'gift' | 'other'; counterparty: string | null; relationshipGroup: string | null; eventDescription: string | null; memo: string | null };

export async function listSupportDetails(householdId: string): Promise<SupportDetail[]> { const supabase = await createClient(); const { data, error } = await supabase.from('transaction_support_details').select('transaction_id,support_kind,eligibility,application_period,receiving_period,payout_cycle,expected_date,amount_per_occurrence,total_expected_amount,status,issuer,contact,source_url,memo').eq('household_id', householdId); if (error) throw new Error(`지원금 상세 조회 실패: ${error.message}`); return (data ?? []).map((r) => ({ transactionId: r.transaction_id, supportKind: r.support_kind, eligibility: r.eligibility, applicationPeriod: r.application_period, receivingPeriod: r.receiving_period, payoutCycle: r.payout_cycle, expectedDate: r.expected_date, amountPerOccurrence: r.amount_per_occurrence, totalExpectedAmount: r.total_expected_amount, status: r.status, issuer: r.issuer, contact: r.contact, sourceUrl: r.source_url, memo: r.memo })); }
export async function listEventDetails(householdId: string): Promise<EventDetail[]> { const supabase = await createClient(); const { data, error } = await supabase.from('transaction_event_details').select('transaction_id,event_type,counterparty,relationship_group,event_description,memo').eq('household_id', householdId); if (error) throw new Error(`경조사 상세 조회 실패: ${error.message}`); return (data ?? []).map((r) => ({ transactionId: r.transaction_id, eventType: r.event_type, counterparty: r.counterparty, relationshipGroup: r.relationship_group, eventDescription: r.event_description, memo: r.memo })); }
export async function upsertSupportDetail(householdId: string, input: Omit<SupportDetail, 'transactionId'> & { transactionId: string }): Promise<void> { const supabase = await createClient(); const { data: transaction, error: transactionError } = await supabase.from('transactions').select('id').eq('id', input.transactionId).eq('household_id', householdId).is('deleted_at', null).maybeSingle(); if (transactionError || !transaction) throw new Error('소속 가구의 거래만 수정할 수 있어요.'); const { error } = await supabase.from('transaction_support_details').upsert({ household_id: householdId, transaction_id: input.transactionId, support_kind: input.supportKind, eligibility: input.eligibility, application_period: input.applicationPeriod, receiving_period: input.receivingPeriod, payout_cycle: input.payoutCycle, expected_date: input.expectedDate, amount_per_occurrence: input.amountPerOccurrence, total_expected_amount: input.totalExpectedAmount, status: input.status, issuer: input.issuer, contact: input.contact, source_url: input.sourceUrl, memo: input.memo }); if (error) throw new Error(`지원금 상세 저장 실패: ${error.message}`); }
export async function upsertEventDetail(householdId: string, input: Omit<EventDetail, 'transactionId'> & { transactionId: string }): Promise<void> { const supabase = await createClient(); const { data: transaction, error: transactionError } = await supabase.from('transactions').select('id').eq('id', input.transactionId).eq('household_id', householdId).is('deleted_at', null).maybeSingle(); if (transactionError || !transaction) throw new Error('소속 가구의 거래만 수정할 수 있어요.'); const { error } = await supabase.from('transaction_event_details').upsert({ household_id: householdId, transaction_id: input.transactionId, event_type: input.eventType, counterparty: input.counterparty, relationship_group: input.relationshipGroup, event_description: input.eventDescription, memo: input.memo }); if (error) throw new Error(`경조사 상세 저장 실패: ${error.message}`); }
