'use client';
import { useActionState } from 'react'; import { createInsuranceAction, endInsuranceAction } from '@/actions/finance-product-actions'; import { FormMessage } from '@/components/FormMessage'; import { INITIAL_ACTION_STATE } from '@/lib/action-result'; import type { HouseholdMember } from '@/lib/household'; import type { Insurance } from '@/lib/insurances'; import type { PaymentMethod } from '@/lib/payment-methods';
const won = new Intl.NumberFormat('ko-KR');
export function InsuranceManager({ insurances, members, paymentMethods }: { insurances: Insurance[]; members: HouseholdMember[]; paymentMethods: PaymentMethod[] }) {
  const [state, action, pending] = useActionState(createInsuranceAction, INITIAL_ACTION_STATE);
  return <div className="flex flex-col gap-5"><p className="rounded-xl bg-[var(--tds-blue-50)] p-4 text-sm">월 보험료와 납부일을 입력하면 납입만기 전까지 월간 예정거래가 자동 생성돼요.</p><form action={action} className="tds-card grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-4"><div className="md:col-span-2 xl:col-span-4"><FormMessage result={state} /></div>
    <Field label="보험사"><input name="insurerName" required className="px-3" /></Field><Field label="보험 종류"><input name="insuranceType" required className="px-3" placeholder="실비, 종신, 자동차" /></Field><Field label="보험명"><input name="productName" required className="px-3" /></Field><Field label="월 보험료"><input name="monthlyPremium" type="number" min="0" step="1" required className="px-3 text-right" /></Field>
    <Field label="가입일"><input name="joinedAt" type="date" required className="px-3" /></Field><Field label="납입만기"><input name="paymentMaturityDate" type="date" className="px-3" /></Field><Field label="보장만기"><input name="coverageMaturityDate" type="date" className="px-3" /></Field><Field label="월 납부일"><input name="paymentDay" type="number" min="1" max="31" step="1" className="px-3" /></Field>
    <Field label="피보험자"><select name="insuredMemberId" className="px-3"><option value="">지정 안 함</option>{members.map((m) => <option key={m.id} value={m.id}>{m.displayName}</option>)}</select></Field><Field label="결제수단"><select name="paymentMethodId" className="px-3"><option value="">지정 안 함</option>{paymentMethods.filter((p) => p.isActive).map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="납부방법 메모"><input name="paymentMethodNote" className="px-3" placeholder="자동이체" /></Field><Field label="연락처"><input name="contact" className="px-3" /></Field>
    <Field label="보장내역"><input name="coverageSummary" className="px-3" /></Field><Field label="비고"><input name="memo" className="px-3" /></Field><button disabled={pending} className="tds-primary-button md:col-span-2 xl:col-span-4">{pending ? '저장 중...' : '보험 추가'}</button></form>
    <div className="grid gap-4 md:grid-cols-2">{insurances.length === 0 && <p className="tds-card p-6 text-sm text-[var(--tds-grey-500)]">등록한 보험이 없어요.</p>}{insurances.map((item) => <InsuranceCard key={item.id} item={item} />)}</div></div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="flex flex-col gap-1 text-sm font-medium">{label}{children}</label>; }
function InsuranceCard({ item }: { item: Insurance }) { const [state, action, pending] = useActionState(endInsuranceAction, INITIAL_ACTION_STATE); const active = item.status === 'active'; return <article className={`tds-card flex flex-col gap-4 p-5 ${active ? '' : 'opacity-65'}`}><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold">{item.productName}</h2><p className="text-sm text-[var(--tds-grey-700)]">{item.insurerName} · {item.insuranceType}</p></div><span className="rounded-full bg-[var(--tds-grey-100)] px-2 py-1 text-xs">{active ? '유지 중' : item.status === 'free' ? '납입완료' : '해지'}</span></div><div><p className="text-xs text-[var(--tds-grey-500)]">월 보험료</p><strong className="text-xl tabular-nums">{won.format(item.monthlyPremium)}원</strong>{item.paymentDay && <span className="ml-2 text-sm text-[var(--tds-grey-700)]">매월 {item.paymentDay}일</span>}</div>{item.coverageSummary && <p className="rounded-xl bg-[var(--tds-blue-50)] p-3 text-sm">{item.coverageSummary}</p>}<p className="text-xs text-[var(--tds-grey-500)]">납입만기 {item.paymentMaturityDate ?? '-'} · 보장만기 {item.coverageMaturityDate ?? '-'}</p>{active && <><form action={action} className="grid grid-cols-2 gap-2"><input type="hidden" name="id" value={item.id} /><button name="status" value="free" disabled={pending} className="secondary-button">납입완료</button><button name="status" value="terminated" disabled={pending} className="secondary-button text-[var(--tds-red-500)]">해지</button></form><FormMessage result={state} /></>}</article>; }
