'use server';
import { revalidatePath } from 'next/cache';
import { fail, ok, type ActionResult } from '@/lib/action-result';
import { getCurrentHouseholdId } from '@/lib/household';
import { createInvestmentTrade, deleteInvestmentTrade, importInvestmentTrades, updateInvestmentTrade } from '@/lib/investment-trades';
const text = (f: FormData, k: string) => String(f.get(k) ?? '').trim();
const amount = (f: FormData, k: string) => { const n = Number(f.get(k)); return Number.isFinite(n) && n >= 0 ? n : null; };
function parse(f: FormData) { const tradeDate = text(f, 'tradeDate'); const assetName = text(f, 'assetName'); const tradeType = text(f, 'tradeType'); const unitPrice = amount(f, 'unitPrice'); const tradeAmount = amount(f, 'tradeAmount'); const fee = amount(f, 'fee'); const settledAmount = amount(f, 'settledAmount'); if (!/^\d{4}-\d{2}-\d{2}$/.test(tradeDate) || !assetName || !['buy', 'sell'].includes(tradeType) || unitPrice === null || tradeAmount === null || tradeAmount <= 0 || fee === null || settledAmount === null) return null; return { tradeDate, assetName, tradeType: tradeType as 'buy' | 'sell', unitPrice, tradeAmount, fee, settledAmount, memo: text(f, 'memo') || null, source: text(f, 'source') || null }; }
const refresh = () => { revalidatePath('/finance'); revalidatePath('/finance/investments'); revalidatePath('/dashboard'); revalidatePath('/monthly'); };
export async function importInvestmentTradesAction(_: ActionResult, f: FormData): Promise<ActionResult> { const raw = text(f, 'trades'); if (!raw) return fail('媛?몄삱 ?ъ옄嫄곕옒媛 ?놁뒿?덈떎.'); try { const trades = JSON.parse(raw) as unknown; if (!Array.isArray(trades) || trades.length === 0 || trades.length > 10_000) return fail('媛?몄삤湲곗? 1~10,000嫄댁쓣 吏?먰븯?⑸땲??'); const valid = trades.filter((trade): trade is Record<string, unknown> => typeof trade === 'object' && trade !== null).map((trade) => ({ tradeDate: String(trade.tradeDate ?? ''), assetName: String(trade.assetName ?? '').trim(), tradeType: trade.tradeType as 'buy' | 'sell', unitPrice: Number(trade.unitPrice), tradeAmount: Number(trade.tradeAmount), fee: Number(trade.fee), settledAmount: Number(trade.settledAmount), memo: null, source: 'Excel' })).filter((trade) => /^\d{4}-\d{2}-\d{2}$/.test(trade.tradeDate) && trade.assetName && ['buy', 'sell'].includes(trade.tradeType) && [trade.unitPrice, trade.tradeAmount, trade.fee, trade.settledAmount].every((value) => Number.isFinite(value) && value >= 0) && trade.tradeAmount > 0); if (valid.length !== trades.length) return fail('吏?먰븯吏 ?딆? ?ъ옄嫄곕옒媛 ?ы븿?섏뼱 ?덉뒿?덈떎.'); await importInvestmentTrades({ householdId: await getCurrentHouseholdId(), trades: valid }); refresh(); return ok(`${valid.length}嫄댁쓣 媛?몄솕?댁슂.`); } catch (e) { return fail(e instanceof Error ? e.message : '?ъ옄嫄곕옒 媛?몄삤湲곗뿉 ?ㅽ뙣?덉뼱??'); } }
export async function createInvestmentTradeAction(_: ActionResult, f: FormData): Promise<ActionResult> { const value = parse(f); if (!value) return fail('투자거래의 필수값을 확인해 주세요.'); try { await createInvestmentTrade({ householdId: await getCurrentHouseholdId(), ...value }); } catch (e) { return fail(e instanceof Error ? e.message : '투자거래 등록에 실패했어요.'); } refresh(); return ok(); }
export async function updateInvestmentTradeAction(_: ActionResult, f: FormData): Promise<ActionResult> { const id = text(f, 'id'); const value = parse(f); if (!id || !value) return fail('투자거래 정보를 확인해 주세요.'); try { await updateInvestmentTrade(id, value); } catch (e) { return fail(e instanceof Error ? e.message : '투자거래 수정에 실패했어요.'); } refresh(); return ok(); }
export async function deleteInvestmentTradeAction(_: ActionResult, f: FormData): Promise<ActionResult> { const id = text(f, 'id'); if (!id) return fail('삭제할 투자거래를 찾을 수 없어요.'); try { await deleteInvestmentTrade(id); } catch (e) { return fail(e instanceof Error ? e.message : '투자거래 삭제에 실패했어요.'); } refresh(); return ok(); }
