'use server';
import { revalidatePath } from 'next/cache';
import { createFinancialGoal, createFinancialTask, updateFinancialTask } from '@/lib/excel-extended-data';
import { getCurrentHouseholdId } from '@/lib/household';
import { fail, ok, type ActionResult } from '@/lib/action-result';
const date = (f: FormData, key: string) => { const value = String(f.get(key) ?? ''); return /^\d{4}-\d{2}-\d{2}$/.test(value) ? value : null; };
const refresh = () => { revalidatePath('/settings'); revalidatePath('/dashboard'); };
export async function createFinancialGoalAction(_p: ActionResult, f: FormData): Promise<ActionResult> { const name = String(f.get('name') ?? '').trim(); const goalYear = Number(f.get('goalYear')); const targetAmount = String(f.get('targetAmount') ?? '') ? Number(f.get('targetAmount')) : null; const targetRatio = String(f.get('targetRatio') ?? '') ? Number(f.get('targetRatio')) / 100 : null; const targetDate = date(f, 'targetDate'); const currentValue = String(f.get('currentValue') ?? '') ? Number(f.get('currentValue')) : null; if (!name || !Number.isInteger(goalYear) || (targetAmount !== null && (!Number.isSafeInteger(targetAmount) || targetAmount < 0)) || (targetRatio !== null && (!Number.isFinite(targetRatio) || targetRatio < 0 || targetRatio > 1))) return fail('목표 정보를 확인해 주세요.'); try { await createFinancialGoal({ householdId: await getCurrentHouseholdId(), goalYear, name, targetAmount, targetRatio, targetDate, currentValue, memo: String(f.get('memo') ?? '').trim() || null }); } catch (e) { return fail(e instanceof Error ? e.message : '목표 추가에 실패했어요.'); } refresh(); return ok('목표를 추가했어요.'); }
export async function createFinancialTaskAction(_p: ActionResult, f: FormData): Promise<ActionResult> { const taskDate = date(f, 'taskDate'); const title = String(f.get('title') ?? '').trim(); if (!taskDate || !title) return fail('일정 날짜와 제목을 확인해 주세요.'); try { await createFinancialTask({ householdId: await getCurrentHouseholdId(), taskDate, title, description: String(f.get('description') ?? '').trim() || null, relatedType: String(f.get('relatedType') ?? '').trim() || null }); } catch (e) { return fail(e instanceof Error ? e.message : '일정 추가에 실패했어요.'); } refresh(); return ok('일정을 추가했어요.'); }
export async function toggleFinancialTaskAction(_p: ActionResult, f: FormData): Promise<ActionResult> { const id = String(f.get('id') ?? ''); if (!id) return fail('일정을 확인해 주세요.'); try { await updateFinancialTask(id, f.get('completed') === 'true'); } catch (e) { return fail(e instanceof Error ? e.message : '일정 변경에 실패했어요.'); } refresh(); return ok(); }
