'use client';

import { useMemo, useState } from 'react';
import type { HomeMonthlyCategory, HomeMonth, HomeRank } from '@/lib/dashboard-home';

const won = new Intl.NumberFormat('ko-KR');
const money = (value: number) => `${won.format(Math.round(value))}원`;
type Detail = { month: string; id: string; label: string; value: number; subcategories: HomeRank[] };

export function DashboardMonthlyDetail({ selectedMonth, monthly, incomeMonthly, incomeCurrent, expenseMonthly, expenseCurrent, expensePayments, transactionDetails }: { selectedMonth: string; monthly: HomeMonth[]; incomeMonthly: HomeMonthlyCategory[]; incomeCurrent: HomeRank[]; expenseMonthly: HomeMonthlyCategory[]; expenseCurrent: HomeRank[]; expensePayments: HomeRank[]; transactionDetails: Detail[] }) {
  const [scope, setScope] = useState<'month' | 'year'>('month');
  const [month, setMonth] = useState(selectedMonth);
  const value = useMemo(() => { if (scope === 'year') return { label: `${selectedMonth.slice(0, 4)}년 전체`, income: monthly.reduce((sum, item) => sum + item.income, 0), consume: monthly.reduce((sum, item) => sum + item.consumption, 0), saving: monthly.reduce((sum, item) => sum + item.saving + item.investment, 0), expense: monthly.reduce((sum, item) => sum + item.consumption + item.financeCost + item.saving + item.investment + item.debtPrincipal, 0), incomeRows: mergeRows(incomeMonthly), expenseRows: mergeRows(expenseMonthly) }; const current = monthly.find((item) => item.month === month); const incomeForMonth = incomeMonthly.find((item) => item.month === month)?.categories ?? []; const expenseForMonth = expenseMonthly.find((item) => item.month === month)?.categories ?? []; return { label: `${month.slice(0, 4)}년 ${Number(month.slice(5, 7))}월`, income: current?.income ?? 0, consume: current?.consumption ?? 0, saving: (current?.saving ?? 0) + (current?.investment ?? 0), expense: (current?.consumption ?? 0) + (current?.financeCost ?? 0) + (current?.saving ?? 0) + (current?.investment ?? 0) + (current?.debtPrincipal ?? 0), incomeRows: incomeForMonth.length ? incomeForMonth : incomeCurrent, expenseRows: expenseForMonth.length ? expenseForMonth : (month === selectedMonth ? expenseCurrent : []) }; }, [scope, month, selectedMonth, monthly, incomeMonthly, incomeCurrent, expenseMonthly, expenseCurrent]);
  const expenseSubcategories = scope === 'year' ? transactionDetails : transactionDetails.filter((detail) => detail.month === month);
  const rows = scope === 'month' && month === selectedMonth ? expenseCurrent : value.expenseRows;
  return <section className="home-monthly-detail" aria-labelledby="home-monthly-detail-title"><div className="home-html-title"><h2 id="home-monthly-detail-title">월별 상세</h2><span>{value.label}</span></div><div className="home-monthly-detail-controls"><div className="home-explorer-tabs"><button type="button" className={scope === 'month' ? 'is-selected' : ''} onClick={() => setScope('month')}>월별</button><button type="button" className={scope === 'year' ? 'is-selected' : ''} onClick={() => setScope('year')}>연간</button></div>{scope === 'month' && <div className="home-month-selector">{monthly.slice(-12).map((item) => <button type="button" key={item.month} className={item.month === month ? 'is-selected' : ''} onClick={() => setMonth(item.month)}>{Number(item.month.slice(5, 7))}월</button>)}</div>}</div><div className="home-flow-kpi-grid"><Kpi label={`수입 · ${value.label}`} value={value.income} meta="총수입" tone="positive" /><Kpi label="소비성지출" value={value.consume} meta={value.income ? `수입의 ${(value.consume / value.income * 100).toFixed(1)}%` : '수입 없음'} tone="negative" /><Kpi label="저축·투자" value={value.saving} meta={value.income ? `저축률 ${(value.saving / value.income * 100).toFixed(1)}%` : '수입 없음'} tone="wealth" /><Kpi label="순현금흐름" value={value.income - value.expense} meta={value.income >= value.expense ? '흑자' : '적자'} tone={value.income >= value.expense ? 'positive' : 'negative'} /></div><UnifiedDetailList incomeRows={value.incomeRows} expenseRows={rows} incomeTotal={value.income} expenseTotal={value.consume} details={expenseSubcategories} /><p className="home-html-note">저축성지출은 소비가 아니라 자산으로 이동하는 금액이므로 소비성지출과 분리했습니다.</p><span className="sr-only">결제수단별 지출 항목 {expensePayments.length}개</span></section>;
}
function Kpi({ label, value, meta, tone }: { label: string; value: number; meta: string; tone: 'positive' | 'negative' | 'wealth' }) { return <article className="tds-card home-html-kpi"><span>{label}</span><strong className={`is-${tone}`}>{money(value)}</strong><small>{meta}</small></article>; }
function UnifiedDetailList({ incomeRows, expenseRows, incomeTotal, expenseTotal, details }: { incomeRows: HomeRank[]; expenseRows: HomeRank[]; incomeTotal: number; expenseTotal: number; details: Detail[] }) { const [expanded, setExpanded] = useState<Set<string>>(new Set()); const rows = [...incomeRows.map((row) => ({ ...row, kind: '수입', total: incomeTotal })), ...expenseRows.map((row) => ({ ...row, kind: '지출', total: expenseTotal }))]; const max = Math.max(1, ...rows.map((row) => row.value)); return <article className="tds-card home-html-card home-unified-detail"><div className="home-html-title"><h3>수입·지출 상세</h3><span>유형을 누르면 하위 항목을 확인할 수 있어요</span></div><div className="home-unified-detail-header"><span>구분</span><span>항목</span><span>금액 · 비중</span></div><div className="home-unified-detail-list">{rows.map((row) => { const detailSubcategories = details.filter((detail) => detail.id === row.id).flatMap((detail) => detail.subcategories); const subcategories = detailSubcategories.length ? detailSubcategories : (row.subcategories ?? []); const key = `${row.kind}-${row.id}`; const isExpanded = expanded.has(key); return <div key={key}><button type="button" className="home-unified-detail-trigger" aria-expanded={isExpanded} onClick={() => setExpanded((current) => { const next = new Set(current); if (next.has(key)) next.delete(key); else next.add(key); return next; })}><span className={`home-flow-kind is-${row.kind === '수입' ? 'income' : 'expense'}`}>{row.kind}</span><span>{row.label}<i><em style={{ width: `${row.value / max * 100}%` }} /></i></span><b>{money(row.value)} · {row.total > 0 ? (row.value / row.total * 100).toFixed(1) : '0.0'}%</b></button>{isExpanded && subcategories.map((sub) => <small className="home-unified-detail-subrow" key={sub.id}><span>{sub.label}</span><b>{money(sub.value)}</b></small>)}</div>; })}</div>{!rows.length && <p className="home-html-note">등록된 수입·지출이 없습니다.</p>}</article>; }
function mergeRows(monthly: HomeMonthlyCategory[]): HomeRank[] { const values = new Map<string, HomeRank>(); monthly.forEach((item) => item.categories.forEach((row) => { const previous = values.get(row.id); const subcategories = new Map<string, HomeRank>((previous?.subcategories ?? []).map((sub) => [sub.id, sub])); (row.subcategories ?? []).forEach((sub) => subcategories.set(sub.id, { ...sub, value: (subcategories.get(sub.id)?.value ?? 0) + sub.value })); values.set(row.id, { ...row, value: (previous?.value ?? 0) + row.value, subcategories: [...subcategories.values()].sort((a, b) => b.value - a.value) }); })); return [...values.values()].sort((a, b) => b.value - a.value); }
