'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import type { HomeMonthlyCategory, HomeMonth, HomeRank } from '@/lib/dashboard-home';

const won = new Intl.NumberFormat('ko-KR');
const money = (value: number) => `${won.format(Math.round(value))}원`;
type Detail = { month: string; id: string; label: string; value: number; subcategories: HomeRank[] };

// monthly/incomeMonthly/expenseMonthly/transactionDetails는 항상 detailYear 한 해(1~12월) 기준으로
// 서버에서 미리 계산돼 내려온다 — 연도를 바꾸면 ?detailYear= 쿼리로 새 서버 렌더를 타지만(새 연도 데이터가
// 필요하므로), 같은 연도 안에서 [월별] 탭의 달을 바꾸는 것과 [월별]/[연간] 탭 전환은 이미 받은 데이터
// 안에서 클라이언트 상태로만 처리된다(추가 서버 왕복 없음).
export function DashboardMonthlyDetail({ selectedMonth, detailYear, initialMonth, availableYears, monthly, incomeMonthly, incomeCurrent, expenseMonthly, expenseCurrent, expensePayments, transactionDetails }: { selectedMonth: string; detailYear: string; initialMonth: string; availableYears: number[]; monthly: HomeMonth[]; incomeMonthly: HomeMonthlyCategory[]; incomeCurrent: HomeRank[]; expenseMonthly: HomeMonthlyCategory[]; expenseCurrent: HomeRank[]; expensePayments: HomeRank[]; transactionDetails: Detail[] }) {
  const [scope, setScope] = useState<'month' | 'year'>('month');
  const [month, setMonth] = useState(initialMonth);
  // 연도 선택기(Link)로 페이지가 새 detailYear/initialMonth로 다시 렌더되면 이 컴포넌트는 그대로 유지된
  // 채 props만 바뀐다 — TransactionDetailDrawer의 syncedTransactionId와 같은 패턴으로, prop이 실제로
  // 바뀐 시점에 렌더 중 내부 상태를 서버가 계산해 내려준 그 연도의 기본 달로 다시 맞춘다.
  const [syncedYear, setSyncedYear] = useState(detailYear);
  if (detailYear !== syncedYear) { setSyncedYear(detailYear); setMonth(initialMonth); }

  const searchParams = useSearchParams();
  const yearHref = (year: number) => { const params = new URLSearchParams(searchParams.toString()); params.set('detailYear', String(year)); return `?${params.toString()}`; };

  const value = useMemo(() => { if (scope === 'year') return { label: `${detailYear}년 전체`, income: monthly.reduce((sum, item) => sum + item.income, 0), consume: monthly.reduce((sum, item) => sum + item.consumption, 0), fixed: monthly.reduce((sum, item) => sum + item.fixedConsumption, 0), variable: monthly.reduce((sum, item) => sum + item.variableConsumption, 0), incomeRows: mergeRows(incomeMonthly), expenseRows: mergeRows(expenseMonthly) }; const current = monthly.find((item) => item.month === month); const incomeForMonth = incomeMonthly.find((item) => item.month === month)?.categories ?? []; const expenseForMonth = expenseMonthly.find((item) => item.month === month)?.categories ?? []; return { label: `${month.slice(0, 4)}년 ${Number(month.slice(5, 7))}월`, income: current?.income ?? 0, consume: current?.consumption ?? 0, fixed: current?.fixedConsumption ?? 0, variable: current?.variableConsumption ?? 0, incomeRows: incomeForMonth.length ? incomeForMonth : incomeCurrent, expenseRows: expenseForMonth.length ? expenseForMonth : (month === selectedMonth ? expenseCurrent : []) }; }, [scope, month, detailYear, selectedMonth, monthly, incomeMonthly, incomeCurrent, expenseMonthly, expenseCurrent]);
  const expenseSubcategories = scope === 'year' ? transactionDetails : transactionDetails.filter((detail) => detail.month === month);
  const rows = scope === 'month' && month === selectedMonth ? expenseCurrent : value.expenseRows;
  {/* 탭 → 연도 선택 → (월별 탭일 때만) 월 선택, 이 순서로 세로로 쌓는다 — 연도 카드가 탭 바로 아래,
   * 월 카드가 그 바로 아래에 오도록(사용자 요청: 선택 카드가 서로 멀리 떨어지지 않게). */}
  return <section className="home-monthly-detail" aria-labelledby="home-monthly-detail-title"><div className="home-html-title"><h2 id="home-monthly-detail-title">월별 상세</h2><span>{value.label}</span></div><div className="home-monthly-detail-controls"><div className="home-explorer-tabs"><button type="button" className={scope === 'month' ? 'is-selected' : ''} onClick={() => setScope('month')}>월별</button><button type="button" className={scope === 'year' ? 'is-selected' : ''} onClick={() => setScope('year')}>연간</button></div><div className="home-month-selector" aria-label="연도 선택">{availableYears.map((year) => <Link key={year} href={yearHref(year)} scroll={false} className={String(year) === detailYear ? 'is-selected' : ''}>{year}년</Link>)}</div>{scope === 'month' && <div className="home-month-selector" aria-label="월 선택">{monthly.map((item) => <button type="button" key={item.month} className={item.month === month ? 'is-selected' : ''} onClick={() => setMonth(item.month)}>{Number(item.month.slice(5, 7))}월</button>)}</div>}</div><div className="home-flow-kpi-grid"><Kpi label={`수입 · ${value.label}`} value={value.income} meta="총수입" tone="positive" /><Kpi label="지출" value={value.consume} meta={value.income ? `수입의 ${(value.consume / value.income * 100).toFixed(1)}%` : '수입 없음'} tone="negative" /><Kpi label="고정비 · 변동비" value={value.fixed} meta={`변동비 ${money(value.variable)}`} tone="wealth" /><Kpi label="순현금흐름" value={value.income - value.consume} meta={value.income >= value.consume ? '흑자' : '적자'} tone={value.income >= value.consume ? 'positive' : 'negative'} /></div><UnifiedDetailList incomeRows={value.incomeRows} expenseRows={rows} incomeTotal={value.income} expenseTotal={value.consume} details={expenseSubcategories} /><span className="sr-only">결제수단별 지출 항목 {expensePayments.length}개</span></section>;
}
function Kpi({ label, value, meta, tone }: { label: string; value: number; meta: string; tone: 'positive' | 'negative' | 'wealth' }) { return <article className="tds-card home-html-kpi"><span>{label}</span><strong className={`is-${tone}`}>{money(value)}</strong><small>{meta}</small></article>; }
function UnifiedDetailList({ incomeRows, expenseRows, incomeTotal, expenseTotal, details }: { incomeRows: HomeRank[]; expenseRows: HomeRank[]; incomeTotal: number; expenseTotal: number; details: Detail[] }) { const [expanded, setExpanded] = useState<Set<string>>(new Set()); const rows = [...incomeRows.map((row) => ({ ...row, kind: '수입', total: incomeTotal })), ...expenseRows.map((row) => ({ ...row, kind: '지출', total: expenseTotal }))]; const max = Math.max(1, ...rows.map((row) => row.value)); return <article className="tds-card home-html-card home-unified-detail"><div className="home-html-title"><h3>수입·지출 상세</h3><span>유형을 누르면 하위 항목을 확인할 수 있어요</span></div><div className="home-unified-detail-header"><span>구분</span><span>항목</span><span>금액 · 비중</span></div><div className="home-unified-detail-list">{rows.map((row) => { const detailSubcategories = details.filter((detail) => detail.id === row.id).flatMap((detail) => detail.subcategories); const subcategories = detailSubcategories.length ? detailSubcategories : (row.subcategories ?? []); const key = `${row.kind}-${row.id}`; const isExpanded = expanded.has(key); return <div key={key}><button type="button" className="home-unified-detail-trigger" aria-expanded={isExpanded} onClick={() => setExpanded((current) => { const next = new Set(current); if (next.has(key)) next.delete(key); else next.add(key); return next; })}><span className={`home-flow-kind is-${row.kind === '수입' ? 'income' : 'expense'}`}>{row.kind}</span><span>{row.label}<i><em style={{ width: `${row.value / max * 100}%` }} /></i></span><b>{money(row.value)} · {row.total > 0 ? (row.value / row.total * 100).toFixed(1) : '0.0'}%</b></button>{isExpanded && subcategories.map((sub) => <small className="home-unified-detail-subrow" key={sub.id}><span>{sub.label}</span><b>{money(sub.value)}</b></small>)}</div>; })}</div>{!rows.length && <p className="home-html-note">등록된 수입·지출이 없습니다.</p>}</article>; }
function mergeRows(monthly: HomeMonthlyCategory[]): HomeRank[] { const values = new Map<string, HomeRank>(); monthly.forEach((item) => item.categories.forEach((row) => { const previous = values.get(row.id); const subcategories = new Map<string, HomeRank>((previous?.subcategories ?? []).map((sub) => [sub.id, sub])); (row.subcategories ?? []).forEach((sub) => subcategories.set(sub.id, { ...sub, value: (subcategories.get(sub.id)?.value ?? 0) + sub.value })); values.set(row.id, { ...row, value: (previous?.value ?? 0) + row.value, subcategories: [...subcategories.values()].sort((a, b) => b.value - a.value) }); })); return [...values.values()].sort((a, b) => b.value - a.value); }
