'use client';

import Link from 'next/link';
import { useState } from 'react';
import type { HomeMonthlyCategory, HomeRank } from '@/lib/dashboard-home';

export function DashboardIncomeExplorer({ month, monthly, current }: { month: string; monthly: HomeMonthlyCategory[]; current: HomeRank[] }) {
  const [view, setView] = useState<'trend' | 'breakdown'>('trend');
  const [expanded, setExpanded] = useState<string | null>(null);
  const total = monthly.reduce((sum, item) => sum + item.total, 0);
  const max = Math.max(1, ...monthly.map((item) => item.total));
  const currentTotal = current.reduce((sum, item) => sum + item.value, 0);
  return <section className="tds-card home-spending-explorer home-income-explorer" aria-labelledby="dashboard-income-title">
    <div className="home-section-heading"><div><h2 id="dashboard-income-title">수입 흐름과 구성</h2><p>확정된 수입만 기준으로 월별 흐름과 수입 항목을 확인합니다.</p></div><Link href="/monthly" prefetch>수입 관리 →</Link></div>
    <div className="home-explorer-controls"><div className="home-explorer-tabs" role="tablist" aria-label="수입 분석 보기"><button type="button" role="tab" aria-selected={view === 'trend'} className={view === 'trend' ? 'is-selected' : ''} onClick={() => { setView('trend'); setExpanded(null); }}>월별 흐름</button><button type="button" role="tab" aria-selected={view === 'breakdown'} className={view === 'breakdown' ? 'is-selected' : ''} onClick={() => { setView('breakdown'); setExpanded(null); }}>이번 달 항목</button></div></div>
    {view === 'trend' ? <div className="home-monthly-spending-list">{monthly.map((item) => { const open = expanded === item.month; const ratio = total > 0 ? item.total / total : 0; return <div key={item.month} className={item.month === month ? 'is-current' : ''}><button type="button" className="home-monthly-spending-trigger" aria-expanded={open} onClick={() => setExpanded(open ? null : item.month)}><span>{item.month.slice(0, 4)}년 {Number(item.month.slice(5, 7))}월</span><span className="home-monthly-spending-track"><span style={{ width: `${item.total / max * 100}%` }} /></span><strong>{Math.round(item.total).toLocaleString('ko-KR')}원 <em>{(ratio * 100).toFixed(1)}%</em></strong><span aria-hidden="true">{open ? '⌃' : '⌄'}</span></button>{open && <div className="home-monthly-category-children">{item.categories.slice(0, 6).map((category) => <Link key={category.id} href={`/monthly?month=${item.month}&category=${category.id}`} prefetch><span>{category.label}</span><strong>{Math.round(category.value).toLocaleString('ko-KR')}원 <em>{(item.total > 0 ? category.value / item.total * 100 : 0).toFixed(1)}%</em></strong></Link>)}</div>}</div>; })}</div> : <div className="home-ranked-list home-explorer-list">{current.slice(0, 8).map((row, index) => { const open = expanded === row.id; const ratio = currentTotal > 0 ? row.value / currentTotal : 0; return <div key={row.id} className="home-explorer-row"><button type="button" className="home-explorer-row-trigger" aria-expanded={open} onClick={() => setExpanded(open ? null : row.id)}><span className="home-rank">{index + 1}</span><span className="home-explorer-row-main"><span className="home-explorer-row-title"><span>{row.label}</span><strong>{Math.round(row.value).toLocaleString('ko-KR')}원 <em>{(ratio * 100).toFixed(1)}%</em></strong></span><span className="home-explorer-track"><span style={{ width: `${row.value / Math.max(1, current[0]?.value ?? 1) * 100}%` }} /></span><small>{row.subcategories?.length ? `하위 ${row.subcategories.length}개` : '상세 내역 보기'}</small></span><span aria-hidden="true" className="home-explorer-chevron">{open ? '⌃' : '⌄'}</span></button>{open && <div className="home-explorer-children">{row.subcategories?.map((sub) => <Link key={sub.id} href={`/monthly?month=${month}&category=${row.id}&subcategory=${sub.id}`} prefetch><span>{sub.label}</span><strong>{Math.round(sub.value).toLocaleString('ko-KR')}원</strong></Link>)}</div>}</div>; })}{!current.length && <p className="home-empty">확정된 수입이 아직 없습니다.</p>}</div>}
  </section>;
}
