import Link from 'next/link';
import { ensureHouseholdForCurrentUser, listHouseholdMembers } from '@/lib/household';
import { monthRangeFromSeoulDateString, todayInSeoul } from '@/lib/date';
import { resolveDashboardRange, UNASSIGNED_DASHBOARD_MEMBER, type DashboardPreset } from '@/lib/dashboard-calculations';
import { getDashboardHomeSummary, type HomeMonth, type HomeRecent, type HomeRank } from '@/lib/dashboard-home';
import { computeCurrentNetWorth, listAssetValueHistory } from '@/lib/snapshots';
import { listFinancialGoals, listFinancialTasks } from '@/lib/excel-extended-data';
import { DashboardPeriodFilters } from './DashboardPeriodFilters';
import { DashboardSpendingExplorer } from './DashboardSpendingExplorer';
import { DashboardNetWorthExplorer } from './DashboardNetWorthExplorer';
import { materializeRecurringRulesForRange } from '@/lib/recurring-rules';
import { getDashboardIncomeSummary } from '@/lib/dashboard-income';
import { DashboardIncomeExplorer } from './DashboardIncomeExplorer';
import { DashboardPrimaryTabs } from './DashboardPrimaryTabs';
import { getDashboardPaymentSummary } from '@/lib/dashboard-payment';
import { getDashboardMonthlySubcategories } from '@/lib/dashboard-subcategories';
import { DashboardFlowTrends } from './DashboardFlowTrends';

const won = new Intl.NumberFormat('ko-KR');
const monthPattern = /^\d{4}-(0[1-9]|1[0-2])$/;
const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const money = (value: number | null | undefined) => value == null ? '-' : `${won.format(Math.round(value))}원`;
const compactMoney = (value: number) => value >= 100_000_000 ? `${(value / 100_000_000).toFixed(value >= 1_000_000_000 ? 1 : 2)}억` : value >= 10_000 ? `${Math.round(value / 10_000).toLocaleString('ko-KR')}만` : won.format(Math.round(value));
const monthLabel = (month: string) => `${Number(month.slice(0, 4))}년 ${Number(month.slice(5, 7))}월`;
const monthBounds = (month: string) => { const range = monthRangeFromSeoulDateString(`${month}-01`); return { from: range.fromDate, to: range.toDate }; };
const shiftMonth = (month: string, offset: number) => { const d = new Date(Date.UTC(Number(month.slice(0, 4)), Number(month.slice(5, 7)) - 1 + offset, 1)); return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, '0')}`; };

export default async function DashboardPage({ searchParams }: { searchParams: Promise<{ month?: string; member?: string; preset?: string; customFrom?: string; customTo?: string }> }) {
  const query = await searchParams; const today = todayInSeoul(); const currentMonth = today.slice(0, 7); const month = query.month && monthPattern.test(query.month) ? query.month : currentMonth; const previousMonth = shiftMonth(month, -1); const trendStart = shiftMonth(month, -23); const bounds = monthBounds(month); const allowedPresets: DashboardPreset[] = ['month', 'last_month', 'ytd', '3m', '6m', '12m', 'custom']; const preset = allowedPresets.includes(query.preset as DashboardPreset) ? query.preset as DashboardPreset : 'month'; const dashboardRange = resolveDashboardRange(bounds.to, preset, query.customFrom, query.customTo); const requestedMember = query.member === UNASSIGNED_DASHBOARD_MEMBER || (query.member && uuidPattern.test(query.member)) ? query.member : undefined; const household = await ensureHouseholdForCurrentUser();
  const members = await listHouseholdMembers(household.id);
  const validMemberForQuery = requestedMember === UNASSIGNED_DASHBOARD_MEMBER || members.some((item) => item.id === requestedMember);
  const memberForQuery = validMemberForQuery ? requestedMember : undefined;
  await materializeRecurringRulesForRange(household.id, `${trendStart}-01`, bounds.to);
  const [summary, incomeSummary, paymentSummary, monthlyDetails, netWorth, assetHistory, goals, tasks] = await Promise.all([
    getDashboardHomeSummary({ householdId: household.id, from: dashboardRange.from < `${trendStart}-01` ? dashboardRange.from : `${trendStart}-01`, to: bounds.to, monthStart: dashboardRange.from, monthEnd: dashboardRange.to, memberId: memberForQuery }), getDashboardIncomeSummary({ householdId: household.id, from: dashboardRange.from < `${trendStart}-01` ? dashboardRange.from : `${trendStart}-01`, to: bounds.to, monthStart: dashboardRange.from, monthEnd: dashboardRange.to, memberId: memberForQuery }), getDashboardPaymentSummary({ householdId: household.id, from: `${trendStart}-01`, to: bounds.to, memberId: memberForQuery }), getDashboardMonthlySubcategories({ householdId: household.id, from: `${trendStart}-01`, to: bounds.to, memberId: memberForQuery }), computeCurrentNetWorth(household.id, today, memberForQuery), listAssetValueHistory(household.id, 36), listFinancialGoals(household.id), listFinancialTasks(household.id, today, `${currentMonth}-31`),
  ]);
  const memberAssetHistory = memberForQuery && memberForQuery !== UNASSIGNED_DASHBOARD_MEMBER ? await listAssetValueHistory(household.id, 36, memberForQuery) : [];
  const validMember = requestedMember === UNASSIGNED_DASHBOARD_MEMBER || members.some((item) => item.id === requestedMember); const member = validMember ? requestedMember : undefined; const memberName = member === UNASSIGNED_DASHBOARD_MEMBER ? '미지정' : members.find((item) => item.id === member)?.displayName ?? '가구 전체'; const monthlyByMonth = new Map(summary.monthly.map((item) => [item.month, item])); const months = Array.from({ length: 12 }, (_, index) => shiftMonth(month, index - 11)); const monthlyTrend = months.map((target) => deriveMonth(monthlyByMonth.get(target) ?? emptyMonth(target))); const monthCurrent = deriveMonth(monthlyByMonth.get(month) ?? emptyMonth(month)); const current = preset === 'month' ? monthCurrent : derivePeriod(summary.monthly, dashboardRange.from, dashboardRange.to); const categoryRows = summary.categories; const paymentRows = summary.payments; const recent = summary.recent; const reviewCount = summary.reviewCount; const plannedCount = summary.plannedCount;
  void memberName;
  const scopedAssetHistory = memberForQuery ? memberAssetHistory : assetHistory; const history = [...scopedAssetHistory.filter((item) => item.snapshotMonth.slice(0, 7) !== currentMonth), { id: 'current', snapshotMonth: `${currentMonth}-01`, totalAssets: netWorth.totalAssets, source: 'live' }].sort((a, b) => a.snapshotMonth.localeCompare(b.snapshotMonth)).slice(-12); const previousAsset = history.at(-2)?.totalAssets ?? null; const assetChange = previousAsset == null ? null : netWorth.totalAssets - previousAsset; const maxAsset = Math.max(1, ...history.map((item) => item.totalAssets)); const debtRatio = netWorth.totalAssets > 0 ? netWorth.totalDebt / netWorth.totalAssets : 0;
  const assetRows = [{ label: '현금·입출금', value: netWorth.cashAssets, color: 'var(--tds-blue-500)' }, { label: '예금', value: netWorth.depositAssets, color: '#6b8afd' }, { label: '적금', value: netWorth.savingsAssets, color: 'var(--tds-green-500)' }, { label: '투자', value: netWorth.investmentAssets, color: '#8b5cf6' }, { label: '부동산·자동차', value: netWorth.nonFinancialAssets, color: '#f59e0b' }].filter((item) => item.value > 0);
  const link = (targetMonth: string, targetMember: string | null | undefined = member) => `/dashboard?month=${targetMonth}${targetMember ? `&member=${targetMember}` : ''}`; const fixedRatio = current.consumption > 0 ? current.fixedConsumption / current.consumption : 0; const variableRatio = current.consumption > 0 ? current.variableConsumption / current.consumption : 0; const budgetRatio = summary.budgetTotal > 0 ? summary.budgetActual / summary.budgetTotal : 0; const actionCount = reviewCount + plannedCount + tasks.filter((task) => !task.completed).length;
  const yearAgo = deriveMonth(monthlyByMonth.get(shiftMonth(month, -12)) ?? emptyMonth(shiftMonth(month, -12)));
  return <div data-page="home" className="tds-page home-page">
    <header className="home-header"><div><p className="home-eyebrow">우리집 재무 · 우리 집 자산</p><h1 className="tds-title">우리 집 재무 현황</h1><p className="home-subtitle">전체 자산과 {monthLabel(month)}의 수입·지출을 한눈에 확인하세요.</p></div><Link href="/quick-add" prefetch className="tds-primary-button home-record-button px-5">+ 거래 기록</Link></header>
    <nav aria-label="조회 기준" className="home-filter-bar"><div className="home-month-row"><div className="home-month-control"><Link aria-label="이전 달" href={link(previousMonth)} prefetch className="home-arrow">←</Link><strong>{monthLabel(month)}</strong>{month < currentMonth ? <Link aria-label="다음 달" href={link(shiftMonth(month, 1))} prefetch className="home-arrow">→</Link> : <span className="home-arrow is-disabled">→</span>}</div><DashboardPeriodFilters month={month} member={member} active={preset} customFrom={query.customFrom} customTo={query.customTo} /></div><div className="home-member-scroll"><Link href={link(month, null)} className={`home-filter-chip ${!member ? 'is-selected' : ''}`}>가구 전체</Link>{members.map((item) => <Link key={item.id} href={link(month, item.id)} className={`home-filter-chip ${member === item.id ? 'is-selected' : ''}`}>{item.displayName}</Link>)}<Link href={link(month, UNASSIGNED_DASHBOARD_MEMBER)} className={`home-filter-chip ${member === UNASSIGNED_DASHBOARD_MEMBER ? 'is-selected' : ''}`}>미지정</Link></div></nav>

    {actionCount > 0 && <section className="home-actions home-notice-bar" aria-labelledby="home-actions-title"><div><p className="home-actions-count">{actionCount}</p><div><h2 id="home-actions-title">먼저 확인할 일이 있어요</h2><p>검토 거래 {reviewCount}건 · 예정 거래 {plannedCount}건 · 미완료 일정 {tasks.filter((task) => !task.completed).length}건</p></div></div><div className="home-action-links"><Link href="/monthly" prefetch>거래 확인</Link><Link href="/settings/recurring" prefetch>예정 관리</Link>{goals.length > 0 && <Link href="/finance" prefetch>목표 보기</Link>}</div></section>}

    <DashboardPrimaryTabs
      asset={<>
        <section className="home-hero-grid"><DashboardNetWorthExplorer netWorth={netWorth.netWorth} totalAssets={netWorth.totalAssets} totalDebt={netWorth.totalDebt} debtRatio={debtRatio} assetChange={assetChange} assetRows={assetRows} history={history.map((item) => ({ month: item.snapshotMonth, value: item.totalAssets }))} maxAsset={maxAsset} /></section>
        <section className="home-detail-grid"><article className="tds-card home-detail-card"><SectionHeading title="전체 자산 추이" description="엑셀의 누적 자산 기록과 현재 평가액을 이어 봅니다." href="/finance" /><div className="home-asset-trend" role="img" aria-label="최근 12개월 총자산 추이">{history.map((item) => <div key={item.id}><strong>{item.id === 'current' ? compactMoney(item.totalAssets) : ''}</strong><span style={{ height: `${Math.max(8, item.totalAssets / maxAsset * 100)}%` }} /><small>{Number(item.snapshotMonth.slice(5, 7))}월</small></div>)}</div></article></section>
      </>}
      monthly={<>
        <section className="home-monthly-detail-lead" aria-labelledby="home-monthly-detail-title"><SectionHeading title={`${monthLabel(month)} 월별 상세`} description="확정된 수입과 지출, 저축·투자 흐름을 먼저 확인합니다." href="/monthly" /><div className="home-flow-kpi-grid"><FlowKpi label="수입" value={current.income} meta="확정 수입" tone="positive" /><FlowKpi label="소비성지출" value={current.consumption + current.financeCost} meta="생활비 + 금융비용" tone="negative" /><FlowKpi label="저축·투자" value={current.saving + current.investment} meta={`저축률 ${current.income > 0 ? ((current.saving + current.investment) / current.income * 100).toFixed(1) : '0.0'}%`} tone="wealth" /><FlowKpi label="순현금흐름" value={current.cashRemaining} meta={current.cashRemaining >= 0 ? '흑자' : '적자'} tone={current.cashRemaining >= 0 ? 'positive' : 'negative'} /></div></section>

        <DashboardSpendingExplorer month={month} categories={categoryRows} payments={paymentRows} total={current.consumption} monthly={months.map((target) => summary.monthlyCategories.find((item) => item.month === target) ?? ({ month: target, total: 0, categories: [] }))} monthlyPayments={months.map((target) => paymentSummary.find((item) => item.month === target) ?? ({ month: target, total: 0, categories: [] }))} monthlyDetails={monthlyDetails.filter((item) => item.month >= months[0] && item.month <= month)} />

        <DashboardIncomeExplorer month={month} monthly={months.map((target) => incomeSummary.monthly.find((item) => item.month === target) ?? ({ month: target, total: 0, categories: [] }))} current={incomeSummary.current} />

        <DashboardFlowTrends monthly={monthlyTrend} selectedMonth={month} />

        <section className="home-detail-grid"><article className="tds-card home-detail-card"><SectionHeading title="최근 기록" description="이번 달 마지막으로 반영된 거래입니다." href="/monthly" /><div className="home-recent-list">{recent.map((transaction) => <TransactionRow key={transaction.id} transaction={transaction} />)}{!recent.length && <Empty text="이번 달 거래가 없습니다." />}</div></article></section>

        <section className="home-detail-grid home-analysis-grid">
      <article className="tds-card home-detail-card"><SectionHeading title="고정비와 변동비" description="이번 달 소비가 반복비와 생활비로 어떻게 구성됐는지 봅니다." href="/monthly" /><div className="home-cost-split"><CostSplitRow label="고정비" value={current.fixedConsumption} ratio={fixedRatio} tone="fixed" /><CostSplitRow label="변동비" value={current.variableConsumption} ratio={variableRatio} tone="variable" /></div><p className="home-analysis-note">분류되지 않은 소비 {money(Math.max(0, current.consumption - current.fixedConsumption - current.variableConsumption))}</p></article>
      <article className="tds-card home-detail-card"><SectionHeading title="예산 대비 실적" description="예산에 반영한 소비만 기준으로 남은 금액을 계산합니다." href="/monthly" /><div className="home-budget-summary"><div><span>예산</span><strong>{money(summary.budgetTotal)}</strong></div><div><span>실적</span><strong>{money(summary.budgetActual)}</strong></div><div><span>잔여</span><strong className={summary.budgetTotal - summary.budgetActual < 0 ? 'is-negative' : ''}>{money(summary.budgetTotal - summary.budgetActual)}</strong></div></div><div className="home-budget-track"><span style={{ width: `${Math.min(100, budgetRatio * 100)}%` }} /></div><p className="home-analysis-note">{summary.budgetTotal > 0 ? `예산의 ${(budgetRatio * 100).toFixed(1)}%를 사용했어요.` : '이번 달 예산을 설정하면 실적을 비교할 수 있어요.'}</p></article>
      <article className="tds-card home-detail-card"><SectionHeading title="재무 목표" description="목표까지 얼마나 왔고, 가까운 일정이 무엇인지 확인합니다." href="/settings" /><div className="home-goal-list">{goals.slice(0, 3).map((goal) => { const target = goal.targetAmount ?? 0; const progress = target > 0 ? Math.min(1, Math.max(0, (goal.currentValue ?? 0) / target)) : 0; return <div className="home-goal-row" key={goal.id}><div><p><strong>{goal.name}</strong><span>{goal.targetDate ?? '기한 없음'}</span></p><div className="home-goal-track"><span style={{ width: `${progress * 100}%` }} /></div></div><b>{target > 0 ? `${(progress * 100).toFixed(0)}%` : '-'}</b></div>; })}{!goals.length && <Empty text="등록된 재무 목표가 없습니다." />}</div></article>
        </section>
        <section className="home-section home-detail-grid">
      <article className="tds-card home-detail-card"><SectionHeading title="전년 동월 비교" description={`${monthLabel(month)}와 ${monthLabel(shiftMonth(month, -12))}의 실제 흐름을 비교합니다.`} /><div className="home-budget-summary"><Comparison label="수입" current={current.income} previous={yearAgo.income} /><Comparison label="생활비" current={current.consumption} previous={yearAgo.consumption} /><Comparison label="자산 형성" current={current.wealthBuilt} previous={yearAgo.wealthBuilt} /></div></article>
        </section>
      </>}
      debt={<section className="home-detail-grid"><article className="tds-card home-detail-card"><SectionHeading title="부채 현황" description="현재 대출 잔액과 월별 원금·이자 흐름을 확인합니다." href="/finance/loans" /><div className="home-budget-summary"><div><span>현재 대출 잔액</span><strong>{money(netWorth.totalDebt)}</strong></div><div><span>총자산 대비</span><strong>{(debtRatio * 100).toFixed(1)}%</strong></div><div><span>이번 달 원금</span><strong>{money(current.debtPrincipal)}</strong></div></div><div className="home-debt-track"><span style={{ width: `${Math.min(100, debtRatio * 100)}%` }} /></div><p className="home-analysis-note">이번 달 금융비용 {money(current.financeCost)} · 대출 상세에서 상환 일정과 조기상환 기록을 관리합니다.</p></article></section>}
      risk={<section className="home-detail-grid"><article className="tds-card home-detail-card"><SectionHeading title="리스크·혜택 점검" description="지금 확인할 항목과 가계에 영향을 주는 혜택을 모아 봅니다." /><div className="home-budget-summary"><div><span>검토 거래</span><strong>{reviewCount}건</strong></div><div><span>예정 거래</span><strong>{plannedCount}건</strong></div><div><span>미완료 일정</span><strong>{tasks.filter((task) => !task.completed).length}건</strong></div></div><div className="home-analysis-note">보험·정부지원금·재무 일정은 각 관리 메뉴에서 상세 내역과 만기·신청 상태를 확인할 수 있습니다.</div><div className="home-action-links"><Link href="/finance/insurances" prefetch>보험 확인</Link><Link href="/settings/data" prefetch>지원금 데이터</Link><Link href="/settings" prefetch>일정 관리</Link></div></article></section>}
    />
  </div>;
}

function SectionHeading({ title, description, href }: { title: string; description: string; href?: string }) { return <div className="home-section-heading"><div><h2>{title}</h2><p>{description}</p></div>{href && <Link href={href} prefetch>전체 보기 →</Link>}</div>; }
function FlowKpi({ label, value, meta, tone }: { label: string; value: number; meta: string; tone: 'positive' | 'negative' | 'wealth' }) { return <article className="tds-card home-flow-kpi"><span>{label}</span><strong className={`is-${tone}`}>{money(value)}</strong><small>{meta}</small></article>; }
function CostSplitRow({ label, value, ratio, tone }: { label: string; value: number; ratio: number; tone: 'fixed' | 'variable' }) { return <div className="home-cost-row"><div><span>{label}</span><strong>{money(value)}</strong></div><div className="home-cost-track"><span className={`is-${tone}`} style={{ width: `${ratio * 100}%` }} /></div><small>{(ratio * 100).toFixed(1)}%</small></div>; }
export function RankedRows({ rows, total, empty, href }: { rows: HomeRank[]; total: number; empty: string; href?: (id: string) => string }) { const max = rows[0]?.value ?? 1; return <div className="home-ranked-list">{rows.slice(0, 6).map((row, index) => { const content = <><span className="home-rank">{index + 1}</span><div><p><span>{row.label}</span><strong>{money(row.value)}</strong></p><div><span style={{ width: `${row.value / max * 100}%` }} /></div><small>{total > 0 ? `${(row.value / total * 100).toFixed(1)}%` : '0%'}</small>{row.subcategories?.length ? <div className="mt-2 border-l-2 border-[var(--tds-grey-200)] pl-3">{row.subcategories.slice(0, 5).map((sub) => <Link key={sub.id} href={href ? `${href(row.id)}&subcategory=${sub.id}` : '#'} className="flex items-center justify-between py-1 text-xs text-[var(--tds-grey-700)] hover:text-[var(--tds-blue-600)]"><span>{sub.label}</span><b>{money(sub.value)}</b></Link>)}</div> : null}</div></>; return row.subcategories?.length ? <div key={row.id} className="home-ranked-row">{content}</div> : href ? <Link key={row.id} href={href(row.id)} className="home-ranked-row" prefetch>{content}</Link> : <div key={row.id} className="home-ranked-row">{content}</div>; })}{!rows.length && <Empty text={empty} />}</div>; }
function TransactionRow({ transaction }: { transaction: HomeRecent }) { const sign = transaction.transactionType === 'income' || transaction.transactionType === 'refund' ? '+' : '-'; return <div className="home-transaction-row"><div><p>{transaction.description}</p><span>{transaction.transactionDate} · {transaction.transactionType === 'income' ? '수입' : transaction.flowClass === 'saving' ? '저축' : transaction.flowClass === 'debt_principal' ? '대출원금' : '지출'}</span></div><strong>{sign}{money(transaction.amount)}</strong></div>; }
function Empty({ text }: { text: string }) { return <p className="home-empty">{text}</p>; }
function Comparison({ label, current, previous }: { label: string; current: number; previous: number }) { const delta = current - previous; return <div><span>{label}</span><strong>{money(current)}</strong><small className={delta < 0 ? 'is-negative' : 'text-[var(--tds-grey-500)]'}>{previous > 0 ? `전년 대비 ${delta >= 0 ? '+' : ''}${money(delta)}` : '전년 데이터 없음'}</small></div>; }
function emptyMonth(month: string): HomeMonth { return { month, income: 0, consumption: 0, fixedConsumption: 0, variableConsumption: 0, saving: 0, investment: 0, debtPrincipal: 0, financeCost: 0 }; }
function deriveMonth(value: HomeMonth) { const wealthBuilt = value.saving + value.investment + value.debtPrincipal; return { ...value, wealthBuilt, cashRemaining: value.income - value.consumption - value.financeCost - wealthBuilt }; }
function derivePeriod(values: HomeMonth[], from: string, to: string) { const months = values.filter((value) => value.month >= from.slice(0, 7) && value.month <= to.slice(0, 7)); return deriveMonth(months.reduce((sum, value) => ({ ...sum, income: sum.income + value.income, consumption: sum.consumption + value.consumption, fixedConsumption: sum.fixedConsumption + value.fixedConsumption, variableConsumption: sum.variableConsumption + value.variableConsumption, saving: sum.saving + value.saving, investment: sum.investment + value.investment, debtPrincipal: sum.debtPrincipal + value.debtPrincipal, financeCost: sum.financeCost + value.financeCost }), emptyMonth(`${from.slice(0, 7)}~${to.slice(0, 7)}`))); }
