import Link from 'next/link';
import { ensureHouseholdForCurrentUser, listHouseholdMembers } from '@/lib/household';
import { monthRangeFromSeoulDateString, todayInSeoul } from '@/lib/date';
import { resolveDashboardRange, UNASSIGNED_DASHBOARD_MEMBER, type DashboardPreset } from '@/lib/dashboard-calculations';
import { getDashboardHomeSummary, type HomeMonth, type HomeRecent, type HomeRank } from '@/lib/dashboard-home';
import { computeCurrentNetWorth, listAssetValueHistory } from '@/lib/snapshots';
import { listFinancialGoals, listFinancialTasks } from '@/lib/excel-extended-data';
import { DashboardPeriodFilters } from './DashboardPeriodFilters';

const won = new Intl.NumberFormat('ko-KR');
const monthPattern = /^\d{4}-(0[1-9]|1[0-2])$/;
const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const money = (value: number | null | undefined) => value == null ? '-' : `${won.format(Math.round(value))}원`;
const compactMoney = (value: number) => value >= 100_000_000 ? `${(value / 100_000_000).toFixed(value >= 1_000_000_000 ? 1 : 2)}억` : value >= 10_000 ? `${Math.round(value / 10_000).toLocaleString('ko-KR')}만` : won.format(Math.round(value));
const monthLabel = (month: string) => `${Number(month.slice(0, 4))}년 ${Number(month.slice(5, 7))}월`;
const monthBounds = (month: string) => { const range = monthRangeFromSeoulDateString(`${month}-01`); return { from: range.fromDate, to: range.toDate }; };
const shiftMonth = (month: string, offset: number) => { const d = new Date(Date.UTC(Number(month.slice(0, 4)), Number(month.slice(5, 7)) - 1 + offset, 1)); return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, '0')}`; };

export default async function DashboardPage({ searchParams }: { searchParams: Promise<{ month?: string; member?: string; preset?: string }> }) {
  const query = await searchParams; const today = todayInSeoul(); const currentMonth = today.slice(0, 7); const month = query.month && monthPattern.test(query.month) ? query.month : currentMonth; const previousMonth = shiftMonth(month, -1); const trendStart = shiftMonth(month, -23); const bounds = monthBounds(month); const allowedPresets: DashboardPreset[] = ['month', 'last_month', 'ytd', '3m', '6m', '12m']; const preset = allowedPresets.includes(query.preset as DashboardPreset) ? query.preset as DashboardPreset : 'month'; const dashboardRange = resolveDashboardRange(bounds.to, preset); const requestedMember = query.member === UNASSIGNED_DASHBOARD_MEMBER || (query.member && uuidPattern.test(query.member)) ? query.member : undefined; const household = await ensureHouseholdForCurrentUser();
  const members = await listHouseholdMembers(household.id);
  const validMemberForQuery = requestedMember === UNASSIGNED_DASHBOARD_MEMBER || members.some((item) => item.id === requestedMember);
  const memberForQuery = validMemberForQuery ? requestedMember : undefined;
  const [summary, netWorth, assetHistory, goals, tasks] = await Promise.all([
    getDashboardHomeSummary({ householdId: household.id, from: dashboardRange.from < `${trendStart}-01` ? dashboardRange.from : `${trendStart}-01`, to: bounds.to, monthStart: bounds.from, monthEnd: bounds.to, memberId: memberForQuery }), computeCurrentNetWorth(household.id, today, memberForQuery), listAssetValueHistory(household.id, 36), listFinancialGoals(household.id), listFinancialTasks(household.id, today, `${currentMonth}-31`),
  ]);
  const validMember = requestedMember === UNASSIGNED_DASHBOARD_MEMBER || members.some((item) => item.id === requestedMember); const member = validMember ? requestedMember : undefined; const memberName = member === UNASSIGNED_DASHBOARD_MEMBER ? '미지정' : members.find((item) => item.id === member)?.displayName ?? '가구 전체'; const monthlyByMonth = new Map(summary.monthly.map((item) => [item.month, item])); const months = Array.from({ length: 12 }, (_, index) => shiftMonth(month, index - 11)); const monthlyTrend = months.map((target) => deriveMonth(monthlyByMonth.get(target) ?? emptyMonth(target))); const current = deriveMonth(monthlyByMonth.get(month) ?? emptyMonth(month)); const previous = deriveMonth(monthlyByMonth.get(previousMonth) ?? emptyMonth(previousMonth)); const maxTrend = Math.max(1, ...monthlyTrend.flatMap((item) => [item.income, item.consumption + item.financeCost, item.wealthBuilt])); const categoryRows = summary.categories; const paymentRows = summary.payments; const recent = summary.recent; const reviewCount = summary.reviewCount; const plannedCount = summary.plannedCount;
  const history = [...assetHistory.filter((item) => item.snapshotMonth.slice(0, 7) !== currentMonth), { id: 'current', snapshotMonth: `${currentMonth}-01`, totalAssets: netWorth.totalAssets, source: 'live' }].sort((a, b) => a.snapshotMonth.localeCompare(b.snapshotMonth)).slice(-12); const previousAsset = history.at(-2)?.totalAssets ?? null; const assetChange = previousAsset == null ? null : netWorth.totalAssets - previousAsset; const maxAsset = Math.max(1, ...history.map((item) => item.totalAssets)); const debtRatio = netWorth.totalAssets > 0 ? netWorth.totalDebt / netWorth.totalAssets : 0;
  const assetRows = [{ label: '현금·입출금', value: netWorth.cashAssets, color: 'var(--tds-blue-500)' }, { label: '예금', value: netWorth.depositAssets, color: '#6b8afd' }, { label: '적금', value: netWorth.savingsAssets, color: 'var(--tds-green-500)' }, { label: '투자', value: netWorth.investmentAssets, color: '#8b5cf6' }, { label: '부동산·자동차', value: netWorth.nonFinancialAssets, color: '#f59e0b' }].filter((item) => item.value > 0); const flowRows = [{ label: '수입', value: current.income, tone: 'positive' }, { label: '생활비', value: current.consumption, tone: 'negative' }, { label: '저축·투자', value: current.saving + current.investment, tone: 'wealth' }, { label: '대출 원금', value: current.debtPrincipal, tone: 'wealth' }, { label: '이자·금융비용', value: current.financeCost, tone: 'negative' }] as const;
  const link = (targetMonth: string, targetMember: string | null | undefined = member) => `/dashboard?month=${targetMonth}${targetMember ? `&member=${targetMember}` : ''}`; const currentConsumptionDelta = current.consumption - previous.consumption; const fixedRatio = current.consumption > 0 ? current.fixedConsumption / current.consumption : 0; const variableRatio = current.consumption > 0 ? current.variableConsumption / current.consumption : 0; const budgetRatio = summary.budgetTotal > 0 ? summary.budgetActual / summary.budgetTotal : 0; const actionCount = reviewCount + plannedCount + tasks.filter((task) => !task.completed).length;
  const yearAgo = deriveMonth(monthlyByMonth.get(shiftMonth(month, -12)) ?? emptyMonth(shiftMonth(month, -12)));
  return <div data-page="home" className="tds-page home-page">
    <DashboardPeriodFilters month={month} member={member} active={preset} />
    <header className="home-header"><div><p className="home-eyebrow">우리집 재무 · 우리 집 자산</p><h1 className="tds-title">자산은 쌓이고, 생활은 감당 가능한가요?</h1><p className="home-subtitle">전체 자산과 {monthLabel(month)}의 돈 흐름을 함께 봅니다.</p></div><Link href="/quick-add" prefetch className="tds-primary-button home-record-button px-5">+ 거래 기록</Link></header>
    <nav aria-label="조회 기준" className="home-filter-bar"><div className="home-month-control"><Link aria-label="이전 달" href={link(previousMonth)} prefetch className="home-arrow">←</Link><strong>{monthLabel(month)}</strong>{month < currentMonth ? <Link aria-label="다음 달" href={link(shiftMonth(month, 1))} prefetch className="home-arrow">→</Link> : <span className="home-arrow is-disabled">→</span>}</div><div className="home-member-scroll"><Link href={link(month, null)} className={`home-filter-chip ${!member ? 'is-selected' : ''}`}>가구 전체</Link>{members.map((item) => <Link key={item.id} href={link(month, item.id)} className={`home-filter-chip ${member === item.id ? 'is-selected' : ''}`}>{item.displayName}</Link>)}<Link href={link(month, UNASSIGNED_DASHBOARD_MEMBER)} className={`home-filter-chip ${member === UNASSIGNED_DASHBOARD_MEMBER ? 'is-selected' : ''}`}>미지정</Link></div></nav>

    <section className="home-hero-grid">
      <article className="home-networth-card"><div className="home-card-heading"><div><p>현재 우리 집 순자산</p><strong>{money(netWorth.netWorth)}</strong></div><Link href="/finance" prefetch>자산 상세 →</Link></div><p className={`home-change ${assetChange != null && assetChange < 0 ? 'is-negative' : ''}`}>{assetChange == null ? '과거 자산 기록을 연결하면 변화를 비교할 수 있어요.' : `직전 기록보다 ${assetChange >= 0 ? '+' : ''}${money(assetChange)}`}</p><div className="home-asset-summary"><SummaryNumber label="총자산" value={netWorth.totalAssets} /><SummaryNumber label="총부채" value={netWorth.totalDebt} /><SummaryNumber label="부채비율" value={debtRatio} percent /></div><div className="home-allocation-bar" aria-label="자산 구성">{assetRows.map((item) => <span key={item.label} style={{ width: `${item.value / Math.max(1, netWorth.totalAssets) * 100}%`, background: item.color }} />)}</div><div className="home-allocation-legend">{assetRows.map((item) => <div key={item.label}><span style={{ background: item.color }} /><p>{item.label}</p><strong>{compactMoney(item.value)}</strong></div>)}</div></article>
      <article className="home-cash-card"><div className="home-card-heading"><div><p>{monthLabel(month)} 남은 현금</p><strong className={current.cashRemaining < 0 ? 'is-negative' : ''}>{money(current.cashRemaining)}</strong></div><Link href="/monthly" prefetch>월간 상세 →</Link></div><p className="home-cash-formula">수입에서 생활비·저축·투자·대출 원리금을 모두 뺀 금액</p><div className="home-flow-list">{flowRows.map((item) => <div key={item.label}><span>{item.label}</span><strong className={`is-${item.tone}`}>{item.label === '수입' ? '+' : '-'}{money(item.value)}</strong></div>)}</div><div className="home-insight"><strong>{currentConsumptionDelta <= 0 ? '생활비가 줄었어요' : '생활비가 늘었어요'}</strong><span>전월보다 {money(Math.abs(currentConsumptionDelta))} {currentConsumptionDelta <= 0 ? '적게' : '많이'} 썼습니다.</span></div></article>
    </section>

    <section className="home-section"><SectionHeading title={`${monthLabel(month)} 돈의 행선지`} description={`${memberName} 기준으로 수입부터 자산 형성까지 한 줄로 연결했습니다.`} /><div className="home-flow-cards"><FlowCard label="들어온 돈" value={current.income} caption="급여·추가수입" /><FlowCard label="생활에 쓴 돈" value={current.consumption + current.financeCost} caption={`생활비 ${compactMoney(current.consumption)} · 이자 ${compactMoney(current.financeCost)}`} /><FlowCard label="자산으로 바뀐 돈" value={current.wealthBuilt} caption={`저축·투자·대출원금`} accent /><FlowCard label="실제로 남은 돈" value={current.cashRemaining} caption="모든 유출 반영" warning={current.cashRemaining < 0} /></div></section>

    <section className="home-section home-trend-card"><SectionHeading title="12개월 돈 흐름" description="월별 수입·생활비·자산형성액을 같은 기준으로 비교합니다." /><div className="home-trend-chart" role="img" aria-label="최근 12개월 수입, 생활비, 자산형성액 막대 차트">{monthlyTrend.map((item) => <div key={item.month} className={`home-trend-month ${item.month === month ? 'is-current' : ''}`}><div className="home-trend-bars"><TrendBar value={item.income} max={maxTrend} tone="income" /><TrendBar value={item.consumption + item.financeCost} max={maxTrend} tone="expense" /><TrendBar value={item.wealthBuilt} max={maxTrend} tone="wealth" /></div><span>{Number(item.month.slice(5, 7))}월</span></div>)}</div><div className="home-chart-legend"><span className="is-income">수입</span><span className="is-expense">생활비·이자</span><span className="is-wealth">자산형성</span></div></section>

    <section className="home-detail-grid"><article className="tds-card home-detail-card"><SectionHeading title="생활비 항목" description="항목을 누르면 해당 월 거래로 이동합니다." href="/monthly" /><RankedRows rows={categoryRows} total={current.consumption} empty="생활비 기록이 없습니다." href={(id) => `/monthly?month=${month}&category=${id}`} /></article><article className="tds-card home-detail-card"><SectionHeading title="카드·결제수단" description="카드, 계좌이체, 현금별 실제 사용액입니다." href="/finance/accounts" /><RankedRows rows={paymentRows} total={current.consumption} empty="결제수단이 연결된 생활비가 없습니다." /></article></section>

    <section className="home-detail-grid"><article className="tds-card home-detail-card"><SectionHeading title="전체 자산 추이" description="엑셀의 누적 자산 기록과 현재 평가액을 이어 봅니다." href="/finance" /><div className="home-asset-trend" role="img" aria-label="최근 12개월 총자산 추이">{history.map((item) => <div key={item.id}><strong>{item.id === 'current' ? compactMoney(item.totalAssets) : ''}</strong><span style={{ height: `${Math.max(8, item.totalAssets / maxAsset * 100)}%` }} /><small>{Number(item.snapshotMonth.slice(5, 7))}월</small></div>)}</div></article><article className="tds-card home-detail-card"><SectionHeading title="최근 기록" description="이번 달 마지막으로 반영된 거래입니다." href="/monthly" /><div className="home-recent-list">{recent.map((transaction) => <TransactionRow key={transaction.id} transaction={transaction} />)}{!recent.length && <Empty text="이번 달 거래가 없습니다." />}</div></article></section>

    <section className="home-actions"><div><p className="home-actions-count">{actionCount}</p><div><h2>확인할 일이 있어요</h2><p>검토 거래 {reviewCount}건 · 예정 거래 {plannedCount}건 · 재무 일정 {tasks.filter((task) => !task.completed).length}건</p></div></div><div className="home-action-links"><Link href="/monthly" prefetch>거래 확인</Link><Link href="/settings/recurring" prefetch>예정 관리</Link>{goals.length > 0 && <Link href="/finance" prefetch>목표 보기</Link>}</div></section>
    <section className="home-detail-grid home-analysis-grid">
      <article className="tds-card home-detail-card"><SectionHeading title="고정비와 변동비" description="이번 달 소비가 반복비와 생활비로 어떻게 구성됐는지 봅니다." href="/monthly" /><div className="home-cost-split"><CostSplitRow label="고정비" value={current.fixedConsumption} ratio={fixedRatio} tone="fixed" /><CostSplitRow label="변동비" value={current.variableConsumption} ratio={variableRatio} tone="variable" /></div><p className="home-analysis-note">분류되지 않은 소비 {money(Math.max(0, current.consumption - current.fixedConsumption - current.variableConsumption))}</p></article>
      <article className="tds-card home-detail-card"><SectionHeading title="예산 대비 실적" description="예산에 반영한 소비만 기준으로 남은 금액을 계산합니다." href="/monthly" /><div className="home-budget-summary"><div><span>예산</span><strong>{money(summary.budgetTotal)}</strong></div><div><span>실적</span><strong>{money(summary.budgetActual)}</strong></div><div><span>잔여</span><strong className={summary.budgetTotal - summary.budgetActual < 0 ? 'is-negative' : ''}>{money(summary.budgetTotal - summary.budgetActual)}</strong></div></div><div className="home-budget-track"><span style={{ width: `${Math.min(100, budgetRatio * 100)}%` }} /></div><p className="home-analysis-note">{summary.budgetTotal > 0 ? `예산의 ${(budgetRatio * 100).toFixed(1)}%를 사용했어요.` : '이번 달 예산을 설정하면 실적을 비교할 수 있어요.'}</p></article>
      <article className="tds-card home-detail-card"><SectionHeading title="재무 목표" description="목표까지 얼마나 왔고, 가까운 일정이 무엇인지 확인합니다." href="/settings" /><div className="home-goal-list">{goals.slice(0, 3).map((goal) => { const target = goal.targetAmount ?? 0; const progress = target > 0 ? Math.min(1, Math.max(0, (goal.currentValue ?? 0) / target)) : 0; return <div className="home-goal-row" key={goal.id}><div><p><strong>{goal.name}</strong><span>{goal.targetDate ?? '기한 없음'}</span></p><div className="home-goal-track"><span style={{ width: `${progress * 100}%` }} /></div></div><b>{target > 0 ? `${(progress * 100).toFixed(0)}%` : '-'}</b></div>; })}{!goals.length && <Empty text="등록된 재무 목표가 없습니다." />}</div></article>
    </section>
    <section className="home-section home-detail-grid">
      <article className="tds-card home-detail-card"><SectionHeading title="전년 동월 비교" description={`${monthLabel(month)}와 ${monthLabel(shiftMonth(month, -12))}의 실제 흐름을 비교합니다.`} /><div className="home-budget-summary"><Comparison label="수입" current={current.income} previous={yearAgo.income} /><Comparison label="생활비" current={current.consumption} previous={yearAgo.consumption} /><Comparison label="자산 형성" current={current.wealthBuilt} previous={yearAgo.wealthBuilt} /></div></article>
    </section>
  </div>;
}

function SectionHeading({ title, description, href }: { title: string; description: string; href?: string }) { return <div className="home-section-heading"><div><h2>{title}</h2><p>{description}</p></div>{href && <Link href={href} prefetch>전체 보기 →</Link>}</div>; }
function SummaryNumber({ label, value, percent = false }: { label: string; value: number; percent?: boolean }) { return <div><span>{label}</span><strong>{percent ? `${(value * 100).toFixed(1)}%` : money(value)}</strong></div>; }
function FlowCard({ label, value, caption, accent = false, warning = false }: { label: string; value: number; caption: string; accent?: boolean; warning?: boolean }) { return <article className={`home-flow-card ${accent ? 'is-accent' : ''} ${warning ? 'is-warning' : ''}`}><p>{label}</p><strong>{money(value)}</strong><span>{caption}</span></article>; }
function CostSplitRow({ label, value, ratio, tone }: { label: string; value: number; ratio: number; tone: 'fixed' | 'variable' }) { return <div className="home-cost-row"><div><span>{label}</span><strong>{money(value)}</strong></div><div className="home-cost-track"><span className={`is-${tone}`} style={{ width: `${ratio * 100}%` }} /></div><small>{(ratio * 100).toFixed(1)}%</small></div>; }
function TrendBar({ value, max, tone }: { value: number; max: number; tone: 'income' | 'expense' | 'wealth' }) { return <span className={`is-${tone}`} title={money(value)} style={{ height: `${Math.max(value > 0 ? 4 : 0, value / max * 100)}%` }} />; }
function RankedRows({ rows, total, empty, href }: { rows: HomeRank[]; total: number; empty: string; href?: (id: string) => string }) { const max = rows[0]?.value ?? 1; return <div className="home-ranked-list">{rows.slice(0, 6).map((row, index) => { const content = <><span className="home-rank">{index + 1}</span><div><p><span>{row.label}</span><strong>{money(row.value)}</strong></p><div><span style={{ width: `${row.value / max * 100}%` }} /></div><small>{total > 0 ? `${(row.value / total * 100).toFixed(1)}%` : '0%'}</small>{row.subcategories?.length ? <div className="mt-2 border-l-2 border-[var(--tds-grey-200)] pl-3">{row.subcategories.slice(0, 5).map((sub) => <Link key={sub.id} href={href ? `${href(row.id)}&subcategory=${sub.id}` : '#'} className="flex items-center justify-between py-1 text-xs text-[var(--tds-grey-700)] hover:text-[var(--tds-blue-600)]"><span>{sub.label}</span><b>{money(sub.value)}</b></Link>)}</div> : null}</div></>; return row.subcategories?.length ? <div key={row.id} className="home-ranked-row">{content}</div> : href ? <Link key={row.id} href={href(row.id)} className="home-ranked-row" prefetch>{content}</Link> : <div key={row.id} className="home-ranked-row">{content}</div>; })}{!rows.length && <Empty text={empty} />}</div>; }
function TransactionRow({ transaction }: { transaction: HomeRecent }) { const sign = transaction.transactionType === 'income' || transaction.transactionType === 'refund' ? '+' : '-'; return <div className="home-transaction-row"><div><p>{transaction.description}</p><span>{transaction.transactionDate} · {transaction.transactionType === 'income' ? '수입' : transaction.flowClass === 'saving' ? '저축' : transaction.flowClass === 'debt_principal' ? '대출원금' : '지출'}</span></div><strong>{sign}{money(transaction.amount)}</strong></div>; }
function Empty({ text }: { text: string }) { return <p className="home-empty">{text}</p>; }
function Comparison({ label, current, previous }: { label: string; current: number; previous: number }) { const delta = current - previous; return <div><span>{label}</span><strong>{money(current)}</strong><small className={delta < 0 ? 'is-negative' : 'text-[var(--tds-grey-500)]'}>{previous > 0 ? `전년 대비 ${delta >= 0 ? '+' : ''}${money(delta)}` : '전년 데이터 없음'}</small></div>; }
function emptyMonth(month: string): HomeMonth { return { month, income: 0, consumption: 0, fixedConsumption: 0, variableConsumption: 0, saving: 0, investment: 0, debtPrincipal: 0, financeCost: 0 }; }
function deriveMonth(value: HomeMonth) { const wealthBuilt = value.saving + value.investment + value.debtPrincipal; return { ...value, wealthBuilt, cashRemaining: value.income - value.consumption - value.financeCost - wealthBuilt }; }
