import Link from 'next/link';
import { listBudgets } from '@/lib/budgets'; import { listCategoriesWithSubcategories } from '@/lib/categories'; import { buildDashboardPeriod, compareMetric, filterDashboardTransactions } from '@/lib/dashboard-calculations'; import { todayInSeoul } from '@/lib/date'; import { ensureHouseholdForCurrentUser } from '@/lib/household'; import { listPaymentMethods } from '@/lib/payment-methods'; import { computeCurrentNetWorth, listRecentSnapshots, type AssetSnapshot } from '@/lib/snapshots'; import { listTransactions, type Transaction } from '@/lib/transactions';

const won = new Intl.NumberFormat('ko-KR'); const MONTH = /^\d{4}-(0[1-9]|1[0-2])$/;
function shiftMonth(month: string, offset: number) { const [y, m] = month.split('-').map(Number); const d = new Date(Date.UTC(y, m - 1 + offset, 1)); return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, '0')}`; }
function bounds(month: string) { const [y, m] = month.split('-').map(Number); const last = new Date(Date.UTC(y, m, 0)).getUTCDate(); return { from: `${month}-01`, to: `${month}-${String(last).padStart(2, '0')}` }; }
const inMonth = (rows: Transaction[], month: string) => rows.filter((t) => t.transactionDate.startsWith(month));

export default async function DashboardPage({ searchParams }: { searchParams: Promise<{ month?: string; drilldown?: string }> }) {
  const query = await searchParams; const currentMonth = todayInSeoul().slice(0, 7); const selectedMonth = query.month && MONTH.test(query.month) ? query.month : currentMonth; const previousMonth = shiftMonth(selectedMonth, -1); const yearAgoMonth = shiftMonth(selectedMonth, -12); const oldestComparisonMonth = shiftMonth(selectedMonth, -23); const selectedBounds = bounds(selectedMonth); const household = await ensureHouseholdForCurrentUser();
  const years = [...new Set(Array.from({ length: 24 }, (_, i) => Number(shiftMonth(selectedMonth, -i).slice(0, 4))))];
  const [allTransactions, categories, paymentMethods, snapshots, currentNetWorth, ...annualBudgets] = await Promise.all([
    listTransactions({ householdId: household.id, fromDate: `${oldestComparisonMonth}-01`, toDate: selectedBounds.to }), listCategoriesWithSubcategories(household.id), listPaymentMethods(household.id), listRecentSnapshots(household.id, 24), computeCurrentNetWorth(household.id, todayInSeoul()), ...years.map((year) => listBudgets(household.id, year)),
  ]);
  const budgets = annualBudgets.flat(); const period = (month: string) => buildDashboardPeriod(inMonth(allTransactions, month), budgets.filter((b) => b.year === Number(month.slice(0, 4)) && b.month === Number(month.slice(5, 7))).map((b) => ({ transactionType: b.transactionType, categoryId: b.categoryId, amount: b.amount })));
  const current = period(selectedMonth); const previous = period(previousMonth); const yearAgo = period(yearAgoMonth); const selectedTransactions = inMonth(allTransactions, selectedMonth);
  const liveSnapshot: AssetSnapshot = { ...currentNetWorth, id: 'live', snapshotMonth: `${currentMonth}-01` };
  const assetFor = (month: string) => month === currentMonth ? liveSnapshot : snapshots.find((s) => s.snapshotMonth === `${month}-01`) ?? null;
  const asset = assetFor(selectedMonth); const previousAsset = assetFor(previousMonth); const yearAgoAsset = assetFor(yearAgoMonth);
  const categoryById = new Map(categories.map((c) => [c.id, c.name])); const paymentById = new Map(paymentMethods.map((p) => [p.id, p.name]));
  const categoryRows = Object.entries(current.spentByCategory).sort((a, b) => b[1] - a[1]); const paymentRows = Object.entries(current.spendingByPaymentMethod).sort((a, b) => b[1] - a[1]); const maxCategory = categoryRows[0]?.[1] ?? 0;
  const currentBudgets = budgets.filter((b) => b.year === Number(selectedMonth.slice(0, 4)) && b.month === Number(selectedMonth.slice(5, 7)) && b.transactionType === 'expense'); const budgetByCategory = new Map<string, number>(); for (const budget of currentBudgets) if (budget.categoryId) budgetByCategory.set(budget.categoryId, (budgetByCategory.get(budget.categoryId) ?? 0) + budget.amount); const budgetRows = [...new Set([...budgetByCategory.keys(), ...Object.keys(current.spentByCategory)])].map((id) => ({ id, name: categoryById.get(id) ?? '미분류', budget: budgetByCategory.get(id) ?? 0, actual: current.spentByCategory[id] ?? 0 })).sort((a, b) => Math.max(b.budget, b.actual) - Math.max(a.budget, a.actual));
  const months = Array.from({ length: 12 }, (_, i) => shiftMonth(selectedMonth, i - 11)); const trends = months.map((month) => ({ month, ...period(month) })); const yoyTrends = months.map((month) => ({ month, current: period(month).consumption, previous: period(shiftMonth(month, -12)).consumption })); const maxFlow = Math.max(1, ...trends.flatMap((t) => [t.income, t.consumption, t.saving, Math.max(0, t.cashRemaining)]));
  const details = filterDashboardTransactions(selectedTransactions, query.drilldown).sort((a, b) => b.amount - a.amount);
  const href = (extra: Record<string, string | undefined>) => { const p = new URLSearchParams({ month: selectedMonth }); for (const [k, v] of Object.entries(extra)) if (v) p.set(k, v); return `/dashboard?${p}`; };
  return <div className="tds-page flex flex-col gap-6">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="tds-title">우리 집 재정을 한눈에 봐요</h1><p className="mt-2 text-sm text-[var(--tds-grey-700)]">실적은 posted 거래만 반영하고 이체는 수입·지출에서 제외해요.</p></div><nav className="flex items-center gap-2"><Link className="tds-chip px-4" href={`/dashboard?month=${previousMonth}`}>←</Link><span className="min-w-28 text-center font-bold">{selectedMonth}</span>{selectedMonth < currentMonth ? <Link className="tds-chip px-4" href={`/dashboard?month=${shiftMonth(selectedMonth, 1)}`}>→</Link> : <span className="tds-chip px-4 opacity-40">→</span>}</nav></header>
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-3 xl:grid-cols-5">
      <Kpi label="총수입" value={current.income} previous={previous.income} yearAgo={yearAgo.income} href={`${href({ drilldown: 'income' })}#details`} />
      <Kpi label="소비성지출" value={current.consumption} previous={previous.consumption} yearAgo={yearAgo.consumption} href={`${href({ drilldown: 'consumption' })}#details`} />
      <Kpi label="저축성지출" value={current.saving} previous={previous.saving} yearAgo={yearAgo.saving} href={`${href({ drilldown: 'saving' })}#details`} />
      <Kpi label="잔여현금흐름" value={current.cashRemaining} previous={previous.cashRemaining} yearAgo={yearAgo.cashRemaining} href={`${href({ drilldown: 'cash' })}#details`} accent />
      <Kpi label="저축률" value={current.savingsRate} previous={previous.savingsRate} yearAgo={yearAgo.savingsRate} percent />
      <Kpi label="예산소진율" value={current.budgetUsageRate} previous={previous.budgetUsageRate} yearAgo={yearAgo.budgetUsageRate} percent />
      <Kpi label="총자산" value={asset?.totalAssets ?? null} previous={previousAsset?.totalAssets ?? null} yearAgo={yearAgoAsset?.totalAssets ?? null} />
      <Kpi label="총부채" value={asset?.totalDebt ?? null} previous={previousAsset?.totalDebt ?? null} yearAgo={yearAgoAsset?.totalDebt ?? null} />
      <Kpi label="순자산" value={asset?.netWorth ?? null} previous={previousAsset?.netWorth ?? null} yearAgo={yearAgoAsset?.netWorth ?? null} href="/finance" accent />
    </section>
    <Insight current={current} topCategory={categoryRows[0] ? categoryById.get(categoryRows[0][0]) ?? '미분류' : null} topAmount={categoryRows[0]?.[1] ?? 0} previous={previous} />
    <section className="tds-card p-5"><h2 className="text-lg font-bold">현금흐름 추이</h2><p className="mt-1 text-sm text-[var(--tds-grey-700)]">최근 12개월 수입·소비·저축·잔여현금</p><div className="mt-5 flex h-48 items-end gap-2 overflow-x-auto">{trends.map((t) => <div key={t.month} className="flex min-w-12 flex-1 flex-col items-center gap-1"><div className="flex h-36 items-end gap-1"><Bar value={t.income} max={maxFlow} color="bg-[var(--tds-blue-500)]" /><Bar value={t.consumption} max={maxFlow} color="bg-[var(--tds-red-500)]" /><Bar value={t.saving} max={maxFlow} color="bg-[var(--tds-green-500)]" /><Bar value={Math.max(0, t.cashRemaining)} max={maxFlow} color="bg-[var(--tds-grey-500)]" /></div><span className="text-[10px] text-[var(--tds-grey-500)]">{t.month.slice(2)}</span></div>)}</div><p className="mt-3 text-xs text-[var(--tds-grey-500)]">● 수입(파랑) ● 소비(빨강) ● 저축(초록) ● 잔여현금(회색)</p></section>
    <div className="grid gap-5 lg:grid-cols-2"><Breakdown title="지출 구성" rows={categoryRows.map(([id, value]) => ({ id, name: categoryById.get(id) ?? '미분류', value, href: href({ drilldown: `category:${id}` }) }))} total={current.consumption} max={maxCategory} /><Breakdown title="결제수단별 소비" rows={paymentRows.map(([id, value]) => ({ id, name: paymentById.get(id) ?? '미지정', value, href: href({ drilldown: `payment:${id}` }) }))} total={current.consumption} max={paymentRows[0]?.[1] ?? 0} /></div>
    <div className="grid gap-5 lg:grid-cols-2"><BudgetActual rows={budgetRows} href={href} /><AssetComposition snapshot={asset} /></div>
    <YoyChart rows={yoyTrends} />
    <NetWorthTrend snapshots={snapshots} />
    {query.drilldown && <section className="tds-card p-5" id="details"><div className="flex justify-between gap-3"><h2 className="text-lg font-bold">원인 거래 {details.length}건</h2><Link href={href({})} className="text-sm font-semibold text-[var(--tds-blue-500)]">닫기</Link></div><div className="mt-4 divide-y divide-[var(--tds-grey-200)]">{details.map((t) => <div key={t.id} className="flex justify-between gap-4 py-3 text-sm"><div><p className="font-semibold">{t.description}</p><p className="text-[var(--tds-grey-500)]">{t.transactionDate} · {t.categoryId ? categoryById.get(t.categoryId) : '미분류'}</p></div><strong className="tabular-nums">{won.format(t.amount)}원</strong></div>)}{details.length === 0 && <p className="py-6 text-sm text-[var(--tds-grey-500)]">해당 거래가 없어요.</p>}</div></section>}
  </div>;
}

function Kpi({ label, value, previous, yearAgo, percent = false, href, accent = false }: { label: string; value: number | null; previous: number | null; yearAgo: number | null; percent?: boolean; href?: string; accent?: boolean }) { const format = (v: number | null) => v === null ? '-' : percent ? `${(v * 100).toFixed(1)}%` : `${won.format(v)}원`; const body = <><p className="text-xs text-[var(--tds-grey-500)]">{label}</p><strong className={`mt-2 block text-xl tabular-nums ${accent ? 'text-[var(--tds-blue-500)]' : ''}`}>{format(value)}</strong>{value !== null && previous !== null && <Delta label="전월" current={value} comparison={previous} percentPoint={percent} />}{value !== null && yearAgo !== null && <Delta label="전년" current={value} comparison={yearAgo} percentPoint={percent} />}</>; return href ? <Link href={href} className="tds-card p-4 transition hover:-translate-y-0.5 hover:shadow-md">{body}</Link> : <div className="tds-card p-4">{body}</div>; }
function Delta({ label, current, comparison, percentPoint }: { label: string; current: number; comparison: number; percentPoint: boolean }) { const d = compareMetric(current, comparison); return <p className="mt-1 text-[11px] text-[var(--tds-grey-500)]">{label} {d.amount >= 0 ? '+' : ''}{percentPoint ? `${(d.amount * 100).toFixed(1)}%p` : `${won.format(d.amount)}원`}{!percentPoint && d.rate !== null ? ` (${(d.rate * 100).toFixed(1)}%)` : ''}</p>; }
function Bar({ value, max, color }: { value: number; max: number; color: string }) { return <div title={`${won.format(value)}원`} className={`w-2 rounded-t ${color}`} style={{ height: `${Math.max(value > 0 ? 3 : 0, value / max * 100)}%` }} />; }
function Insight({ current, previous, topCategory, topAmount }: { current: ReturnType<typeof buildDashboardPeriod>; previous: ReturnType<typeof buildDashboardPeriod>; topCategory: string | null; topAmount: number }) { const consumption = compareMetric(current.consumption, previous.consumption); return <section className="grid gap-3 md:grid-cols-3"><p className="rounded-2xl bg-[var(--tds-blue-50)] p-4 text-sm">{topCategory ? `${topCategory}이(가) 이번 달 소비 1위예요. ${won.format(topAmount)}원을 썼어요.` : '아직 이번 달 소비가 없어요.'}</p><p className="rounded-2xl bg-[var(--tds-grey-100)] p-4 text-sm">소비는 전월보다 {consumption.amount >= 0 ? '늘었어요' : '줄었어요'}: {won.format(Math.abs(consumption.amount))}원.</p><p className="rounded-2xl bg-[var(--tds-grey-100)] p-4 text-sm">저축률 {current.savingsRate === null ? '-' : `${(current.savingsRate * 100).toFixed(1)}%`}{current.savingsRateVariance === null ? '' : ` · 목표 대비 ${current.savingsRateVariance >= 0 ? '+' : ''}${(current.savingsRateVariance * 100).toFixed(1)}%p`}</p></section>; }
function Breakdown({ title, rows, total, max }: { title: string; rows: { id: string; name: string; value: number; href: string }[]; total: number; max: number }) { return <section className="tds-card p-5"><h2 className="text-lg font-bold">{title}</h2><div className="mt-4 flex flex-col gap-3">{rows.slice(0, 8).map((r) => <Link href={`${r.href}#details`} key={r.id} className="block"><div className="flex justify-between text-sm"><span>{r.name}</span><span className="tabular-nums">{won.format(r.value)}원 · {total > 0 ? (r.value / total * 100).toFixed(1) : 0}%</span></div><div className="mt-1 h-2 rounded-full bg-[var(--tds-grey-100)]"><div className="h-2 rounded-full bg-[var(--tds-blue-500)]" style={{ width: `${max > 0 ? r.value / max * 100 : 0}%` }} /></div></Link>)}{rows.length === 0 && <p className="text-sm text-[var(--tds-grey-500)]">표시할 소비가 없어요.</p>}</div></section>; }
function BudgetActual({ rows, href }: { rows: { id: string; name: string; budget: number; actual: number }[]; href: (extra: Record<string, string | undefined>) => string }) { const max = Math.max(1, ...rows.flatMap((r) => [r.budget, r.actual])); return <section className="tds-card p-5"><h2 className="text-lg font-bold">예산 대 실제</h2><p className="mt-1 text-sm text-[var(--tds-grey-700)]">카테고리별 소비 예산 소진</p><div className="mt-4 flex flex-col gap-4">{rows.slice(0, 8).map((r) => <Link key={r.id} href={`${href({ drilldown: `category:${r.id}` })}#details`}><div className="flex justify-between text-sm"><span>{r.name}</span><span className={r.actual > r.budget ? 'font-semibold text-[var(--tds-red-500)]' : ''}>{won.format(r.actual)} / {won.format(r.budget)}원</span></div><div className="mt-1 grid gap-1"><div className="h-1.5 rounded bg-[var(--tds-grey-200)]" style={{ width: `${r.budget / max * 100}%` }} /><div className="h-1.5 rounded bg-[var(--tds-blue-500)]" style={{ width: `${r.actual / max * 100}%` }} /></div></Link>)}{rows.length === 0 && <p className="text-sm text-[var(--tds-grey-500)]">등록된 예산이 없어요.</p>}</div></section>; }
function AssetComposition({ snapshot }: { snapshot: AssetSnapshot | null }) { const rows = snapshot ? [{ name: '현금성', value: snapshot.cashAssets }, { name: '예금', value: snapshot.depositAssets }, { name: '적금', value: snapshot.savingsAssets }, { name: '투자', value: snapshot.investmentAssets }, { name: '기타', value: snapshot.nonFinancialAssets }].filter((r) => r.value > 0) : []; const max = Math.max(1, ...rows.map((r) => r.value)); return <section className="tds-card p-5"><h2 className="text-lg font-bold">자산 구성</h2><p className="mt-1 text-sm text-[var(--tds-grey-700)]">선택 월 스냅샷 기준</p><div className="mt-4 flex flex-col gap-3">{rows.map((r) => <div key={r.name}><div className="flex justify-between text-sm"><span>{r.name}</span><span>{won.format(r.value)}원 · {snapshot && snapshot.totalAssets > 0 ? (r.value / snapshot.totalAssets * 100).toFixed(1) : 0}%</span></div><div className="mt-1 h-2 rounded bg-[var(--tds-grey-100)]"><div className="h-2 rounded bg-[var(--tds-blue-500)]" style={{ width: `${r.value / max * 100}%` }} /></div></div>)}{rows.length === 0 && <p className="text-sm text-[var(--tds-grey-500)]">표시할 자산 스냅샷이 없어요.</p>}</div></section>; }
function YoyChart({ rows }: { rows: { month: string; current: number; previous: number }[] }) { const max = Math.max(1, ...rows.flatMap((r) => [r.current, r.previous])); return <section className="tds-card p-5"><h2 className="text-lg font-bold">소비 전년 비교</h2><p className="mt-1 text-sm text-[var(--tds-grey-700)]">월별 최근 12개월과 전년 동월</p><div className="mt-5 flex h-44 items-end gap-2 overflow-x-auto">{rows.map((r) => <div key={r.month} className="flex min-w-12 flex-1 flex-col items-center"><div className="flex h-32 items-end gap-1"><Bar value={r.current} max={max} color="bg-[var(--tds-blue-500)]" /><Bar value={r.previous} max={max} color="bg-[var(--tds-grey-300)]" /></div><span className="mt-1 text-[10px]">{r.month.slice(2)}</span></div>)}</div><p className="mt-3 text-xs text-[var(--tds-grey-500)]">● 최근(파랑) ● 전년 동월(회색)</p></section>; }
function NetWorthTrend({ snapshots }: { snapshots: AssetSnapshot[] }) { const rows = [...snapshots].reverse().slice(-12); const max = Math.max(1, ...rows.map((s) => Math.max(Math.abs(s.totalAssets), Math.abs(s.totalDebt), Math.abs(s.netWorth)))); return <section className="tds-card p-5"><h2 className="text-lg font-bold">순자산 추이</h2><p className="mt-1 text-sm text-[var(--tds-grey-700)]">저장한 월말 스냅샷 기준</p><div className="mt-5 flex h-44 items-end gap-3 overflow-x-auto">{rows.map((s) => <div key={s.id} className="flex min-w-16 flex-1 flex-col items-center"><div className="flex h-32 items-end gap-1"><Bar value={Math.abs(s.totalAssets)} max={max} color="bg-[var(--tds-blue-500)]" /><Bar value={Math.abs(s.totalDebt)} max={max} color="bg-[var(--tds-red-500)]" /><Bar value={Math.abs(s.netWorth)} max={max} color="bg-[var(--tds-green-500)]" /></div><span className="mt-1 text-[10px]">{s.snapshotMonth.slice(2, 7)}</span></div>)}{rows.length === 0 && <p className="self-center text-sm text-[var(--tds-grey-500)]">자산·금융에서 이번 달 스냅샷을 저장해 주세요.</p>}</div></section>; }
