'use client';

import { useActionState, useState } from 'react';
import { createRecurringRuleAction } from '@/actions/recurring-rule-actions';
import { INITIAL_ACTION_STATE } from '@/lib/action-result';
import { FormMessage } from '@/components/FormMessage';
import type { CategoryWithSubcategories } from '@/lib/categories';
import type { PaymentMethod } from '@/lib/payment-methods';

export function RecurringRuleForm({ categories, paymentMethods }: { categories: CategoryWithSubcategories[]; paymentMethods: PaymentMethod[] }) {
  const [state, formAction, pending] = useActionState(createRecurringRuleAction, INITIAL_ACTION_STATE); const [frequency, setFrequency] = useState('monthly'); const [categoryId, setCategoryId] = useState(''); const selectedCategory = categories.find((category) => category.id === categoryId);
  return <form action={formAction} className="recurring-form">
    <FormMessage result={state} />
    <fieldset><legend>기본 정보</legend><div className="recurring-form-grid"><Field label="항목명" required><input name="description" required placeholder="예: 월세, 급여, 넷플릭스" className="px-3 py-2" /></Field><Field label="기본 금액" required><input name="amount" type="number" min="1" step="1" inputMode="numeric" required placeholder="금액을 입력하세요" className="px-3 py-2 text-right" /></Field><Field label="종류"><select name="sourceType" className="px-3 py-2"><option value="manual">일반 반복거래</option><option value="subscription">구독</option><option value="salary">급여</option></select></Field><Field label="거래 유형"><select name="transactionType" className="px-3 py-2"><option value="expense">지출</option><option value="income">수입</option><option value="saving">저축</option><option value="investment">투자</option><option value="debt_principal">대출 원금</option><option value="finance_cost">금융 비용</option><option value="transfer">이체</option></select></Field></div></fieldset>
    <fieldset><legend>반복 일정</legend><div className="recurring-form-grid"><Field label="시작일" required><input name="startDate" type="date" required className="px-3 py-2" aria-label="반복 시작일" /></Field><Field label="종료일"><input name="endDate" type="date" className="px-3 py-2" aria-label="반복 종료일 (선택)" /></Field><Field label="반복 주기"><select name="frequency" value={frequency} onChange={(event) => setFrequency(event.target.value)} className="px-3 py-2"><option value="monthly">매월</option><option value="weekly">매주</option><option value="yearly">매년</option><option value="custom">사용자 지정</option></select></Field><Field label="반복 간격" required><input name="intervalCount" type="number" min="1" step="1" defaultValue="1" required placeholder="1" className="px-3 py-2 text-right" /></Field>{frequency === 'monthly' && <Field label="매월 납부일" required><input name="dayOfMonth" type="number" min="1" max="31" defaultValue="1" required placeholder="1~31" className="px-3 py-2 text-right" /></Field>}</div></fieldset>
    <fieldset><legend>분류와 결제수단 <span>(선택)</span></legend><div className="recurring-form-grid"><Field label="비용 성격"><select name="costBehavior" className="px-3 py-2"><option value="">카테고리 기본값</option><option value="fixed">고정비</option><option value="variable">변동비</option></select></Field><Field label="카테고리"><select name="categoryId" value={categoryId} onChange={(event) => setCategoryId(event.target.value)} className="px-3 py-2"><option value="">선택 안 함</option>{categories.filter((category) => category.isActive).map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></Field><Field label="소분류"><select key={categoryId} name="subcategoryId" disabled={!selectedCategory} className="px-3 py-2"><option value="">선택 안 함</option>{selectedCategory?.subcategories.filter((subcategory) => subcategory.isActive).map((subcategory) => <option key={subcategory.id} value={subcategory.id}>{subcategory.name}</option>)}</select></Field><Field label="결제수단"><select name="paymentMethodId" className="px-3 py-2"><option value="">선택 안 함</option>{paymentMethods.filter((method) => method.isActive).map((method) => <option key={method.id} value={method.id}>{method.name}</option>)}</select></Field></div></fieldset>
    <button type="submit" disabled={pending} className="tds-primary-button">{pending ? '저장 중…' : '반복 항목 저장'}</button>
  </form>;
}

function Field({ label, required = false, children }: { label: string; required?: boolean; children: React.ReactNode }) { return <label className="form-field"><span>{label}{required && <em>필수</em>}</span>{children}</label>; }
