'use client';

import { useActionState } from 'react';
import { createHouseholdMemberAction, updateHouseholdMemberAction } from '@/actions/household-actions';
import { createFinancialGoalAction, createFinancialTaskAction, toggleFinancialTaskAction } from '@/actions/planning-actions';
import { FormMessage } from '@/components/FormMessage';
import { INITIAL_ACTION_STATE } from '@/lib/action-result';
import type { HouseholdMember } from '@/lib/household';
import type { FinancialGoal, FinancialTask } from '@/lib/excel-extended-data';

const memberTypeName = { self: '본인', spouse: '배우자', child: '자녀', other: '기타' } as const;
const won = (value: number | null) => value == null ? '-' : `${value.toLocaleString('ko-KR')}원`;

export function HouseholdPlanning({ members, goals, tasks }: { members: HouseholdMember[]; goals: FinancialGoal[]; tasks: FinancialTask[] }) {
  const [memberState, memberAction, memberPending] = useActionState(createHouseholdMemberAction, INITIAL_ACTION_STATE);
  const [goalState, goalAction, goalPending] = useActionState(createFinancialGoalAction, INITIAL_ACTION_STATE);
  const [taskState, taskAction, taskPending] = useActionState(createFinancialTaskAction, INITIAL_ACTION_STATE);
  return <div className="flex flex-col gap-6">
    <section className="tds-card p-5"><h2 className="text-lg font-bold">가족 구성원</h2><p className="mt-1 text-sm text-[var(--tds-grey-700)]">명의자와 비용 대상을 구분해 우리 집 재무를 분석해요.</p><form action={memberAction} className="mt-4 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><input name="displayName" required placeholder="이름 또는 표시명" className="px-3" /><select name="memberType" defaultValue="spouse" className="px-3"><option value="self">본인</option><option value="spouse">배우자</option><option value="child">자녀</option><option value="other">기타</option></select><button disabled={memberPending} className="tds-primary-button px-4">{memberPending ? '추가 중…' : '구성원 추가'}</button></form><FormMessage result={memberState} /><div className="mt-4 divide-y divide-[var(--tds-grey-200)]">{members.map((member) => <MemberRow key={member.id} member={member} />)}</div></section>
    <div className="grid gap-6 lg:grid-cols-2">
      <section className="tds-card p-5"><h2 className="text-lg font-bold">재무 목표</h2><p className="mt-1 text-sm text-[var(--tds-grey-700)]">대시보드에서 목표 진행 상황을 확인해요.</p><form action={goalAction} className="mt-4 grid gap-3 sm:grid-cols-2"><input name="name" required placeholder="목표명" className="px-3" /><input name="goalYear" type="number" min="2000" max="2200" defaultValue={new Date().getFullYear()} className="px-3" /><input name="targetAmount" type="number" min="0" step="1" placeholder="목표 금액" className="px-3 text-right" /><input name="currentValue" type="number" min="0" step="1" placeholder="현재 금액" className="px-3 text-right" /><input name="targetRatio" type="number" min="0" max="100" step="0.1" placeholder="목표 저축률(%)" className="px-3 text-right" /><input name="targetDate" type="date" className="px-3" /><input name="memo" placeholder="메모" className="px-3 sm:col-span-2" /><button disabled={goalPending} className="tds-primary-button sm:col-span-2">{goalPending ? '추가 중…' : '목표 추가'}</button></form><FormMessage result={goalState} /><div className="mt-4 divide-y divide-[var(--tds-grey-200)]">{goals.length === 0 ? <p className="py-4 text-sm text-[var(--tds-grey-500)]">등록한 목표가 없어요.</p> : goals.map((goal) => <div key={goal.id} className="py-3"><p className="font-semibold">{goal.name}</p><p className="mt-1 text-sm text-[var(--tds-grey-700)]">현재 {won(goal.currentValue)} · 목표 {won(goal.targetAmount)}{goal.targetDate ? ` · ${goal.targetDate}` : ''}</p></div>)}</div></section>
      <section className="tds-card p-5"><h2 className="text-lg font-bold">재무 일정</h2><p className="mt-1 text-sm text-[var(--tds-grey-700)]">납부일·점검일·신청기한을 기록해요.</p><form action={taskAction} className="mt-4 grid gap-3 sm:grid-cols-2"><input name="taskDate" type="date" required className="px-3" /><input name="title" required placeholder="일정 제목" className="px-3" /><input name="relatedType" placeholder="관련 유형 (예: 보험)" className="px-3" /><input name="description" placeholder="설명" className="px-3" /><button disabled={taskPending} className="tds-primary-button sm:col-span-2">{taskPending ? '추가 중…' : '일정 추가'}</button></form><FormMessage result={taskState} /><div className="mt-4 divide-y divide-[var(--tds-grey-200)]">{tasks.length === 0 ? <p className="py-4 text-sm text-[var(--tds-grey-500)]">등록한 일정이 없어요.</p> : tasks.map((task) => <TaskRow key={task.id} task={task} />)}</div></section>
    </div>
  </div>;
}

function MemberRow({ member }: { member: HouseholdMember }) { const [state, action, pending] = useActionState(updateHouseholdMemberAction, INITIAL_ACTION_STATE); return <form action={action} className="flex flex-wrap items-center gap-2 py-3"><input type="hidden" name="id" value={member.id} /><input name="displayName" defaultValue={member.displayName} className="min-w-32 flex-1 px-2 py-2 text-sm" aria-label={`${member.displayName} 이름`} /><select name="memberType" defaultValue={member.memberType} className="px-2 py-2 text-sm"><option value="self">본인</option><option value="spouse">배우자</option><option value="child">자녀</option><option value="other">기타</option></select><label className="flex items-center gap-1 text-xs text-[var(--tds-grey-700)]"><input type="checkbox" name="isActive" defaultChecked={member.isActive || member.memberType === 'self'} disabled={member.memberType === 'self'} />활성</label><button disabled={pending} className="secondary-button px-3 text-xs">{pending ? '저장…' : '저장'}</button><span className="text-xs">{memberTypeName[member.memberType]}</span><FormMessage result={state} /></form>; }
function TaskRow({ task }: { task: FinancialTask }) { const [state, action, pending] = useActionState(toggleFinancialTaskAction, INITIAL_ACTION_STATE); return <form action={action} className={`flex items-center gap-3 py-3 ${task.completed ? 'opacity-60' : ''}`}><input type="hidden" name="id" value={task.id} /><input type="hidden" name="completed" value={String(!task.completed)} /><button disabled={pending} className="h-5 w-5 rounded border" aria-label={`${task.title} ${task.completed ? '미완료로 표시' : '완료로 표시'}`}>{task.completed ? '✓' : ''}</button><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{task.title}</p><p className="text-xs text-[var(--tds-grey-500)]">{task.taskDate}{task.relatedType ? ` · ${task.relatedType}` : ''}</p></div><FormMessage result={state} /></form>; }
