'use client';
import { useActionState } from 'react';
import { createHouseholdMemberAction, updateHouseholdMemberAction } from '@/actions/household-actions';
import { createFinancialGoalAction, createFinancialTaskAction, toggleFinancialTaskAction } from '@/actions/planning-actions';
import { AddDrawer } from '@/components/Drawer';
import { FormMessage } from '@/components/FormMessage';
import { INITIAL_ACTION_STATE } from '@/lib/action-result';
import type { HouseholdMember } from '@/lib/household';
import type { FinancialGoal, FinancialTask } from '@/lib/excel-extended-data';
const won = (value: number | null) => value == null ? '-' : `${value.toLocaleString('ko-KR')}원`;
export function HouseholdPlanning({ members, goals, tasks }: { members: HouseholdMember[]; goals: FinancialGoal[]; tasks: FinancialTask[] }) { return <div className="flex flex-col gap-6"><section className="tds-card p-5"><Header title="가족 구성원" description="명의자와 비용 귀속을 구분해 우리 집 재무를 정확히 관리합니다." /><div className="mt-4 flex justify-end"><MemberDrawer /></div><div className="mt-4 divide-y divide-[var(--tds-grey-200)]">{members.map((member) => <MemberRow key={member.id} member={member} />)}</div></section><div className="grid gap-6 lg:grid-cols-2"><section className="tds-card p-5"><Header title="재무 목표" description="대시보드에서 목표 진행 상황을 확인할 수 있습니다." /><div className="mt-4 flex justify-end"><GoalDrawer /></div><div className="mt-4 divide-y divide-[var(--tds-grey-200)]">{goals.length === 0 ? <Empty text="등록된 목표가 없습니다." /> : goals.map((goal) => <div key={goal.id} className="py-3"><p className="font-semibold">{goal.name}</p><p className="mt-1 text-sm text-[var(--tds-grey-700)]">현재 {won(goal.currentValue)} · 목표 {won(goal.targetAmount)}{goal.targetDate ? ` · ${goal.targetDate}` : ''}</p></div>)}</div></section><section className="tds-card p-5"><Header title="재무 일정" description="납부일과 점검일을 기록하고 완료 여부를 관리합니다." /><div className="mt-4 flex justify-end"><TaskDrawer /></div><div className="mt-4 divide-y divide-[var(--tds-grey-200)]">{tasks.length === 0 ? <Empty text="등록된 일정이 없습니다." /> : tasks.map((task) => <TaskRow key={task.id} task={task} />)}</div></section></div></div>; }
function Header({ title, description }: { title: string; description: string }) { return <><h2 className="text-lg font-bold">{title}</h2><p className="mt-1 text-sm text-[var(--tds-grey-700)]">{description}</p></>; }
function Empty({ text }: { text: string }) { return <p className="py-4 text-sm text-[var(--tds-grey-500)]">{text}</p>; }
function MemberDrawer() { const [state, action, pending] = useActionState(createHouseholdMemberAction, INITIAL_ACTION_STATE); return <AddDrawer title="가족 구성원 추가" triggerLabel="구성원 추가"><form action={action} className="grid gap-4"><FormMessage result={state} /><Field label="이름"><input name="displayName" required placeholder="이름 또는 표시명" /></Field><Field label="관계"><select name="memberType" defaultValue="spouse"><option value="self">본인</option><option value="spouse">배우자</option><option value="child">자녀</option><option value="other">기타</option></select></Field><button disabled={pending} className="tds-primary-button">{pending ? '저장 중...' : '구성원 추가'}</button></form></AddDrawer>; }
function GoalDrawer() { const [state, action, pending] = useActionState(createFinancialGoalAction, INITIAL_ACTION_STATE); return <AddDrawer title="재무 목표 추가" triggerLabel="목표 추가"><form action={action} className="grid gap-4"><FormMessage result={state} /><Field label="목표명"><input name="name" required placeholder="예: 주택 마련" /></Field><Field label="목표 연도"><input name="goalYear" type="number" min="2000" max="2200" defaultValue={new Date().getFullYear()} required /></Field><Field label="목표 금액"><input name="targetAmount" type="number" min="0" step="1" placeholder="0" /></Field><Field label="현재 금액"><input name="currentValue" type="number" min="0" step="1" placeholder="0" /></Field><Field label="목표 비율"><input name="targetRatio" type="number" min="0" max="100" step="0.1" placeholder="예: 30" /></Field><Field label="목표일"><input name="targetDate" type="date" /></Field><Field label="메모"><input name="memo" placeholder="메모 (선택)" /></Field><button disabled={pending} className="tds-primary-button">{pending ? '저장 중...' : '목표 추가'}</button></form></AddDrawer>; }
function TaskDrawer() { const [state, action, pending] = useActionState(createFinancialTaskAction, INITIAL_ACTION_STATE); return <AddDrawer title="재무 일정 추가" triggerLabel="일정 추가"><form action={action} className="grid gap-4"><FormMessage result={state} /><Field label="일정일"><input name="taskDate" type="date" required /></Field><Field label="일정 제목"><input name="title" required placeholder="예: 보험료 납부 확인" /></Field><Field label="관련 유형"><input name="relatedType" placeholder="예: 보험" /></Field><Field label="설명"><input name="description" placeholder="설명 (선택)" /></Field><button disabled={pending} className="tds-primary-button">{pending ? '저장 중...' : '일정 추가'}</button></form></AddDrawer>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="flex flex-col gap-1 text-sm font-medium">{label}{children}</label>; }
function MemberRow({ member }: { member: HouseholdMember }) { const memberTypeLabel = { self: '본인', spouse: '배우자', child: '자녀', other: '기타' }[member.memberType] ?? '기타'; return <div className="flex items-center justify-between gap-3 py-3"><div className="min-w-0"><p className="truncate text-sm font-semibold">{member.displayName}</p><p className="mt-1 text-xs text-[var(--tds-grey-500)]">{memberTypeLabel} · {member.isActive ? '활성' : '비활성'}</p></div><MemberEditDrawer member={member} /></div>; }
function MemberEditDrawer({ member }: { member: HouseholdMember }) { const [state, action, pending] = useActionState(updateHouseholdMemberAction, INITIAL_ACTION_STATE); return <AddDrawer title="가족 구성원 변경" triggerLabel="변경"><form action={action} className="grid gap-4"><FormMessage result={state} /><input type="hidden" name="id" value={member.id} /><Field label="이름"><input name="displayName" defaultValue={member.displayName} required placeholder="이름 또는 표시명" /></Field><Field label="관계"><select name="memberType" defaultValue={member.memberType}><option value="self">본인</option><option value="spouse">배우자</option><option value="child">자녀</option><option value="other">기타</option></select></Field><label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" name="isActive" defaultChecked={member.isActive || member.memberType === 'self'} disabled={member.memberType === 'self'} />활성 상태</label><button disabled={pending} className="tds-primary-button">{pending ? '저장 중...' : '변경 저장'}</button></form></AddDrawer>; }
function TaskRow({ task }: { task: FinancialTask }) { const [state, action, pending] = useActionState(toggleFinancialTaskAction, INITIAL_ACTION_STATE); return <form action={action} className={`flex items-center gap-3 py-3 ${task.completed ? 'opacity-60' : ''}`}><input type="hidden" name="id" value={task.id} /><input type="hidden" name="completed" value={String(!task.completed)} /><button disabled={pending} className="h-5 w-5 rounded border" aria-label={`${task.title} 완료 상태 변경`}>{task.completed ? '✓' : ''}</button><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{task.title}</p><p className="text-xs text-[var(--tds-grey-500)]">{task.taskDate}{task.relatedType ? ` · ${task.relatedType}` : ''}</p></div><FormMessage result={state} /></form>; }
