import Link from 'next/link'; import { todayInSeoul } from '@/lib/date'; import { ensureHouseholdForCurrentUser } from '@/lib/household'; import { calculateNetWorthChange } from '@/lib/net-worth'; import { computeCurrentNetWorth, listRecentSnapshots } from '@/lib/snapshots'; import { SnapshotButton } from './SnapshotButton';
const won = new Intl.NumberFormat('ko-KR');
export default async function FinancePage() { const household = await ensureHouseholdForCurrentUser(); const today = todayInSeoul(); const [summary, snapshots] = await Promise.all([computeCurrentNetWorth(household.id, today), listRecentSnapshots(household.id)]); const thisMonth = `${today.slice(0, 7)}-01`; const previous = snapshots.find((s) => s.snapshotMonth < thisMonth); const change = previous ? calculateNetWorthChange(summary.netWorth, previous.netWorth) : null; return <div className="tds-page"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="tds-title">자산과 금융을 모아서 봐요</h1><p className="mt-2 text-sm text-[var(--tds-grey-700)]">계좌·상품·기타자산에서 대출을 뺀 현재 우리 집 재산이에요.</p></div><SnapshotButton /></div>
  <section className="mt-6 grid gap-4 md:grid-cols-3"><Kpi label="총자산" value={summary.totalAssets} /><Kpi label="총부채" value={summary.totalDebt} /><Kpi label="순자산" value={summary.netWorth} accent detail={change ? `전월 대비 ${change.amount >= 0 ? '+' : ''}${won.format(change.amount)}원${change.rate === null ? '' : ` (${(change.rate * 100).toFixed(1)}%)`}` : '이번 달 자산을 기록하면 다음 달 변화와 비교할 수 있어요.'} /></section>
  <section className="tds-card mt-4 grid grid-cols-2 gap-4 p-5 md:grid-cols-5"><Mini label="계좌" value={summary.cashAssets} /><Mini label="예금" value={summary.depositAssets} /><Mini label="적금" value={summary.savingsAssets} /><Mini label="투자" value={summary.investmentAssets} /><Mini label="비금융자산" value={summary.nonFinancialAssets} /></section>
  <div className="mt-6 grid gap-4 md:grid-cols-2"><Menu href="/finance/accounts" title="계좌·증권" text="입출금·저축·CMA 등 계좌의 현재 잔액을 관리해요" /><Menu href="/finance/savings" title="예금·적금" text="이자, 만기 수령액과 반복납입" /><Menu href="/finance/loans" title="대출" text="상환표, 월 원금·이자와 현재 잔액" /><Menu href="/finance/insurances" title="보험" text="보장내역, 보험료와 만기" /><Menu href="/finance/assets" title="기타자산" text="부동산·자동차·귀금속 평가액" /><Menu href="/finance/investments" title="투자 거래" text="업비트 매수·매도 이력과 자산별 흐름" /></div></div>; }
function Kpi({ label, value, accent, detail }: { label: string; value: number; accent?: boolean; detail?: string }) { return <div className="tds-card p-5"><p className="text-sm text-[var(--tds-grey-500)]">{label}</p><strong className={`mt-2 block text-2xl tabular-nums ${accent ? 'text-[var(--tds-blue-500)]' : ''}`}>{won.format(value)}원</strong>{detail && <p className="mt-2 text-xs text-[var(--tds-grey-700)]">{detail}</p>}</div>; }
function Mini({ label, value }: { label: string; value: number }) { return <div><p className="text-xs text-[var(--tds-grey-500)]">{label}</p><strong className="tabular-nums">{won.format(value)}원</strong></div>; }
function Menu({ href, title, text }: { href: string; title: string; text: string }) { return <Link href={href} className="tds-card p-6 transition hover:-translate-y-0.5 hover:shadow-lg"><span className="text-sm font-semibold text-[var(--tds-blue-500)]">사용 가능</span><h2 className="mt-2 text-xl font-bold">{title}</h2><p className="mt-2 text-sm text-[var(--tds-grey-700)]">{text}</p></Link>; }
