'use client';

import { useActionState } from 'react';
import { AddDrawer } from '@/components/Drawer';
import { ConfirmSubmitButton } from '@/components/ConfirmSubmitButton';
import { FormMessage } from '@/components/FormMessage';
import { INITIAL_ACTION_STATE } from '@/lib/action-result';
import { createInvestmentTradeAction, deleteInvestmentTradeAction, updateInvestmentTradeAction } from '@/actions/investment-actions';
import type { InvestmentTrade } from '@/lib/excel-extended-data';
import { summarizeInvestmentTrades } from '@/lib/investment-calculations';

const won = new Intl.NumberFormat('ko-KR');

export function InvestmentTradeManager({ trades, today }: { trades: InvestmentTrade[]; today: string }) {
  const summary = summarizeInvestmentTrades(trades);
  return <div className="tds-page"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="tds-title">투자거래</h1><p className="mt-2 text-sm text-[var(--tds-grey-700)]">매수·매도 거래를 기록하고 투자 흐름을 관리합니다.</p></div><TradeDrawer title="투자거래 추가" triggerLabel="투자거래 추가" today={today} /></div><div className="mt-6 grid gap-3 md:grid-cols-5"><Kpi label="거래 건수" value={`${won.format(trades.length)}건`} /><Kpi label="총 매수 정산액" value={`${won.format(Math.round(summary.buyAmount))}원`} /><Kpi label="총 매도 정산액" value={`${won.format(Math.round(summary.sellAmount))}원`} /><Kpi label="총 수수료" value={`${won.format(Math.round(summary.fees))}원`} /><Kpi label="순현금흐름" value={`${summary.netCashFlow >= 0 ? '+' : ''}${won.format(Math.round(summary.netCashFlow))}원`} accent={summary.netCashFlow >= 0} /></div><section className="tds-card mt-5 p-5"><h2 className="text-lg font-bold">거래 목록</h2>{trades.length === 0 ? <p className="mt-4 text-sm text-[var(--tds-grey-500)]">등록된 투자거래가 없습니다.</p> : <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr className="border-b text-xs text-[var(--tds-grey-500)]"><th className="py-3">일자</th><th>종목</th><th>구분</th><th className="text-right">거래금액</th><th className="text-right">수수료</th><th className="text-right">정산금액</th><th /></tr></thead><tbody>{trades.slice(0, 100).map((trade) => <TradeRow key={trade.id} trade={trade} today={today} />)}</tbody></table></div>}</section></div>;
}
function Kpi({ label, value, accent = false }: { label: string; value: string; accent?: boolean }) { return <div className="tds-card p-5"><p className="text-sm text-[var(--tds-grey-500)]">{label}</p><strong className={`mt-2 block text-xl tabular-nums ${accent ? 'text-[var(--tds-blue-600)]' : ''}`}>{value}</strong></div>; }
function TradeRow({ trade, today }: { trade: InvestmentTrade; today: string }) { return <tr className="border-b border-[var(--tds-grey-100)]"><td className="whitespace-nowrap py-3">{trade.tradeDate}</td><td>{trade.assetName}</td><td>{trade.tradeType === 'buy' ? '매수' : '매도'}</td><td className="text-right tabular-nums">{won.format(trade.tradeAmount)}원</td><td className="text-right tabular-nums">{won.format(Math.round(trade.fee))}원</td><td className="text-right tabular-nums">{won.format(Math.round(trade.settledAmount))}원</td><td className="pl-3 text-right"><TradeDrawer title="투자거래 수정" triggerLabel="수정" today={today} trade={trade} /><DeleteTrade tradeId={trade.id} /></td></tr>; }
function TradeDrawer({ title, triggerLabel, today, trade }: { title: string; triggerLabel: string; today: string; trade?: InvestmentTrade }) { const [state, action, pending] = useActionState(trade ? updateInvestmentTradeAction : createInvestmentTradeAction, INITIAL_ACTION_STATE); return <AddDrawer title={title} triggerLabel={triggerLabel}><form action={action} className="grid gap-4"><FormMessage result={state} />{trade && <input type="hidden" name="id" value={trade.id} />}<Field label="거래일"><input name="tradeDate" type="date" defaultValue={trade?.tradeDate ?? today} required /></Field><Field label="종목명"><input name="assetName" defaultValue={trade?.assetName} required placeholder="예: 삼성전자, 비트코인" /></Field><Field label="거래구분"><select name="tradeType" defaultValue={trade?.tradeType ?? 'buy'}><option value="buy">매수</option><option value="sell">매도</option></select></Field><Field label="단가"><input name="unitPrice" type="number" min="0" step="0.00000001" defaultValue={trade?.unitPrice ?? 0} required placeholder="0" /></Field><Field label="거래금액"><input name="tradeAmount" type="number" min="1" step="1" defaultValue={trade?.tradeAmount} required placeholder="0" /></Field><Field label="수수료"><input name="fee" type="number" min="0" step="0.00000001" defaultValue={trade?.fee ?? 0} required placeholder="0" /></Field><Field label="정산금액"><input name="settledAmount" type="number" min="0" step="0.00000001" defaultValue={trade?.settledAmount ?? 0} required placeholder="0" /></Field><Field label="메모"><input name="memo" defaultValue={trade?.memo ?? ''} placeholder="메모 (선택)" /></Field><Field label="출처"><input name="source" defaultValue={trade?.source ?? ''} placeholder="출처 (선택)" /></Field><button type="submit" disabled={pending} className="tds-primary-button">{pending ? '저장 중…' : '저장'}</button></form></AddDrawer>; }
function DeleteTrade({ tradeId }: { tradeId: string }) { const [state, action, pending] = useActionState(deleteInvestmentTradeAction, INITIAL_ACTION_STATE); return <form action={action} className="mt-2"><input type="hidden" name="id" value={tradeId} /><ConfirmSubmitButton disabled={pending} className="text-xs font-semibold text-[var(--tds-red-500)]" title="투자 거래를 삭제할까요?" description="삭제한 거래는 복구할 수 없습니다." confirmLabel="삭제">{pending ? '삭제 중…' : '삭제'}</ConfirmSubmitButton><FormMessage result={state} /></form>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="flex flex-col gap-1 text-sm font-medium">{label}{children}</label>; }
