import type { RecurringRule, RecurringSourceType } from '@/lib/recurring-rules';
import { listTransactions } from '@/lib/transactions';

const sourceLabel: Record<RecurringSourceType, string> = { insurance: '보험료', saving: '적금납입', loan: '대출상환', subscription: '구독', salary: '급여', support: '정부지원금', manual: '일반 반복' };
const statusLabel = { active: '사용 중', paused: '일시중지', ended: '종료' } as const;

export async function ProductRecurringInfo({ householdId, rules, sourceType, sourceIds }: { householdId: string; rules: RecurringRule[]; sourceType: RecurringSourceType; sourceIds: string[] }) {
  const linked = rules.filter((rule) => rule.sourceType === sourceType && rule.sourceId && sourceIds.includes(rule.sourceId));
  const transactions = linked.length ? await listTransactions({ householdId, recurringRuleIds: linked.map((rule) => rule.id) }) : [];
  return <section className="tds-card p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-bold">연결된 반복 거래</h2><p className="mt-1 text-sm text-[var(--tds-grey-700)]">상품에서 자동 생성된 거래의 원천과 확정 상태를 확인합니다.</p></div><span className="text-sm font-semibold text-[var(--tds-blue-600)]">{linked.length}건</span></div>{linked.length === 0 ? <p className="mt-4 text-sm text-[var(--tds-grey-500)]">연결된 반복 거래가 없습니다.</p> : <div className="mt-4 grid gap-2">{linked.map((rule) => { const ruleTransactions = transactions.filter((transaction) => transaction.recurringRuleId === rule.id); const planned = ruleTransactions.filter((transaction) => transaction.status === 'planned').length; const posted = ruleTransactions.filter((transaction) => transaction.status === 'posted').length; return <div key={rule.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-[var(--tds-grey-100)] px-4 py-3"><div><p className="font-semibold">{rule.description}</p><p className="text-xs text-[var(--tds-grey-500)]">{rule.defaultAmount.toLocaleString('ko-KR')}원 · {sourceLabel[rule.sourceType]} · {rule.startDate}{rule.endDate ? ` ~ ${rule.endDate}` : '부터'}</p><p className="mt-1 text-xs text-[var(--tds-grey-500)]">예정 {planned}건 · 확정 {posted}건</p></div><div className="flex items-center gap-2"><span className="tds-chip">{statusLabel[rule.status]}</span><a href={`/monthly?recurringRule=${rule.id}`} className="text-xs font-semibold text-[var(--tds-blue-600)]">거래 보기</a></div></div>; })}</div>}</section>;
}
