import { describe, expect, it } from 'vitest'; import { buildDashboardPeriod, compareMetric, filterDashboardTransactions, resolveDashboardRange } from '@/lib/dashboard-calculations'; import type { Transaction } from '@/lib/transactions';
const transaction = (overrides: Partial<Transaction>): Transaction => ({ id: '1', householdId: 'h', transactionDate: '2026-08-01', transactionType: 'expense', flowClass: 'consumption', costBehavior: 'variable', paymentMethodId: null, categoryId: null, subcategoryId: null, amount: 100, description: 't', memo: null, includeInBudget: true, needsReview: false, recurringRuleId: null, recurringOccurrenceId: null, status: 'posted', ...overrides });
describe('dashboard calculations', () => {
  it('compares against the absolute previous value and handles zero', () => { expect(compareMetric(120, 100)).toEqual({ amount: 20, rate: 0.2 }); expect(compareMetric(10, 0)).toEqual({ amount: 10, rate: null }); });
  it('groups consumption by payment method', () => { const result = buildDashboardPeriod([transaction({ paymentMethodId: 'card', amount: 300 }), transaction({ transactionType: 'income', flowClass: 'cash_in', paymentMethodId: 'card', amount: 500 })], []); expect(result.spendingByPaymentMethod).toEqual({ card: 300 }); expect(result.consumption).toBe(300); });
  // 2026-09: 환불/취소는 별도 transaction_type이 아니라 그 거래 자체의 status
  // ('refunded'/'cancelled')이므로 posted 필터에서 이미 완전히 제외된다 — 금액을
  // 빼는(subtract) 게 아니라 애초에 합산되지 않는다.
  it('excludes cancelled/refunded rows from payment method spending entirely', () => { const result = buildDashboardPeriod([transaction({ paymentMethodId: 'card', amount: 300 }), transaction({ paymentMethodId: 'card', amount: 80, status: 'refunded' }), transaction({ paymentMethodId: 'card', amount: 50, status: 'cancelled' })], []); expect(result.consumption).toBe(300); expect(result.spendingByPaymentMethod).toEqual({ card: 300 }); });
  // 2026-09: 참고 거래(flow_class='excluded', 사용자 지시)는 결제수단이 있어도 소비성지출/
  // 결제수단별 지출 위젯에는 기본적으로 안 잡힌다 — "카드 사용액"은 대시보드 RPC의 별도
  // referenceCount/referenceCardAmount 필드로만 제공된다.
  it('excludes reference transactions from consumption and payment-method spending', () => { const result = buildDashboardPeriod([transaction({ paymentMethodId: 'card', amount: 300 }), transaction({ transactionType: 'reference', flowClass: 'excluded', paymentMethodId: 'card', amount: 400 })], []); expect(result.consumption).toBe(300); expect(result.spendingByPaymentMethod).toEqual({ card: 300 }); });
  it('drills down by KPI, category and payment method', () => { const rows = [transaction({ id: 'expense', categoryId: 'food', paymentMethodId: 'card' }), transaction({ id: 'income', transactionType: 'income', flowClass: 'cash_in' })]; expect(filterDashboardTransactions(rows, 'income').map((r) => r.id)).toEqual(['income']); expect(filterDashboardTransactions(rows, 'category:food').map((r) => r.id)).toEqual(['expense']); expect(filterDashboardTransactions(rows, 'payment:card').map((r) => r.id)).toEqual(['expense']); });
  it('resolves presets with equal previous and prior-year periods', () => { expect(resolveDashboardRange('2026-08-29', 'month')).toEqual({ from: '2026-08-01', to: '2026-08-29', previousFrom: '2026-07-03', previousTo: '2026-07-31', yearAgoFrom: '2025-08-01', yearAgoTo: '2025-08-29' }); expect(resolveDashboardRange('2026-08-29', 'ytd')).toMatchObject({ from: '2026-01-01', to: '2026-08-29', yearAgoFrom: '2025-01-01', yearAgoTo: '2025-08-29' }); });
  it('clamps leap-day year comparisons and validates custom ranges', () => { expect(resolveDashboardRange('2024-02-29', 'month').yearAgoTo).toBe('2023-02-28'); expect(resolveDashboardRange('2026-08-29', 'custom', '2026-03-10', '2026-03-20')).toMatchObject({ from: '2026-03-10', to: '2026-03-20', previousFrom: '2026-02-27', previousTo: '2026-03-09' }); });
});
